can_eth_gw Gateway Module: ce_gw_main.h File Reference
ce_gw_main.h File Reference
Core
Control Area Network - Ethernet - Gateway - Haeder.
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/list.h>
#include <linux/types.h>
#include <linux/skbuff.h>
#include "ce_gw_dev.h"
#include "ce_gw_netlink.h"
#include <uapi/linux/can.h>
#include <uapi/linux/if_arp.h>
#include <linux/can/core.h>
#include <linux/can/error.h>
#include <linux/slab.h>
#include <linux/if_ether.h>
#include <linux/netdevice.h>
Data Structures
struct ce_gw_job
#define CE_GW_TYPE_MAX (__CE_GW_TYPE_MAX - 1)
enum ce_gw_type {
CE_GW_TYPE_NONE, CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_TCP,
CE_GW_TYPE_UDP, __CE_GW_TYPE_MAX
}
Type of the Gateway.
struct hlist_head * ce_gw_get_job_list (void)
getter for HLIST_HEAD(ce_gw_job_list)
struct can_frame * ce_gw_alloc_can_frame (void)
allocates memory for the can frame
void ce_gw_free_can_frame (struct can_frame *memory)
frees memory allocated for can_frame
struct canfd_frame * ce_gw_alloc_canfd_frame (void)
allocates memory for a canfd frame
void ce_gw_free_canfd_frame (struct canfd_frame *memory)
frees memory allocated for can_frame
struct can_frame * ce_gw_get_header_can (canid_t can_id, __u8 can_dlc, __u8 *payload)
builds a can header in SFF (standart frame format) or EFF (extended frame formate) with the given information
struct canfd_frame * ce_gw_get_header_canfd (canid_t id, __u8 len, __u8 flags, __u8 res0, __u8 res1, __u8 *data)
struct sk_buff * ce_gw_can_to_eth (unsigned char *dest, unsigned char *source, __be16 type, struct sk_buff *can_buffer, struct net_device *net)
converts sk buffer including can frame into sk buffer including ethernet_frame
struct sk_buff * ce_gw_canfd_to_eth (unsigned char *dest, unsigned char *source, __be16 type, struct sk_buff *canfd_skb, struct net_device *net)
converts sk buffer including canfd frame into sk buffer including ethernet frame
struct sk_buff * ce_gw_eth_to_can (canid_t id, struct sk_buff *eth_buff, struct net_device *net)
converst sk_buffer including an ethernet frame to sk_buffer including a can_frame
struct sk_buff * ce_gw_eth_to_canfd (canid_t id, __u8 flags, __u8 res0, __u8 res1, struct sk_buff *eth_skb, struct net_device *net)
converst sk buffer including an ethernet frame to sk buffer including a canfd frame
void ce_gw_can_rcv (struct sk_buff *can_skb, void *data)
The gateway function for incoming CAN frames Receive CAN frame –> process –> send to ETH dev (skbuffer, struct receiver->data)
void ce_gw_eth_rcv (struct sk_buff *eth_skb, void *data)
The gateway function for incoming ETH frames Receive skb from ETH dev –> process –> send to CAN bus.
int ce_gw_create_route (int src_ifindex, int dst_ifindex, enum ce_gw_type rt_type, u32 flags)
int ce_gw_remove_route (u32 id)
Detailed Description
Control Area Network - Ethernet - Gateway - Haeder.
Author
Stefan Smarzly (stefa.nosp@m.n.sm.nosp@m.arzly.nosp@m.@in..nosp@m.tum.d.nosp@m.e)
Date
May, 2013
Copyright
GNU Public License v3 or higher
Definition in file ce_gw_main.h.
Macro Definition Documentation
#define CE_GW_TYPE_MAX (__CE_GW_TYPE_MAX - 1)
Definition at line 61 of file ce_gw_main.h.
Enumeration Type Documentation
enum ce_gw_type
Type of the Gateway.
Enumerator
CE_GW_TYPE_NONE
No Type. Should normally not be used.
CE_GW_TYPE_ETH
Convert CAN header to Ethernet header Payload of CAN header must contain an IP header
CE_GW_TYPE_NET
Copy complete CAN Frame into Ethernet payload e.g use CAN as Network Layer (Layer 3) protocol.
CE_GW_TYPE_TCP
Convert CAN header into an IP/TCP package
CE_GW_TYPE_UDP
Convert CAN header into an IP/UDP package
__CE_GW_TYPE_MAX
Maximum Type Number + 1
Definition at line 51 of file ce_gw_main.h.
                 {
     CE_GW_TYPE_NONE,
     CE_GW_TYPE_ETH,
     CE_GW_TYPE_NET,
     CE_GW_TYPE_TCP,
     CE_GW_TYPE_UDP,
     __CE_GW_TYPE_MAX,
 };
Function Documentation
int ce_gw_create_route (int src_ifindex, int dst_ifindex, enum ce_gw_type rt_type, u32 flags)
Definition at line 915 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_is_registered_dev(), ce_gw_register_can_src(), ce_gw_register_eth_src(), ce_gw_job::dev, ce_gw_job::dropped_frames, ce_gw_job::dst, ce_gw_job::flags, ce_gw_job::handled_frames, ce_gw_job::id, job_count, ce_gw_job::list, ce_gw_job::src, and ce_gw_job::type.
Referenced by ce_gw_netlink_add().
 {
     int err = 0;
     struct ce_gw_job *gwj;
     gwj = kmem_cache_alloc(ce_gw_job_cache, GFP_KERNEL);
     gwj->id = job_count++;
     gwj->handled_frames = 0;
     gwj->dropped_frames = 0;
     err = -ENODEV;
     gwj->src.dev = dev_get_by_index(&init_net, src_ifindex);
     gwj->dst.dev = dev_get_by_index(&init_net, dst_ifindex);
     if (!gwj->src.dev || !gwj->dst.dev)
         goto clean_exit;
     gwj->type = rt_type;
     gwj->flags = flags;
     /* TEST: pre-filled values */
     gwj->can_rcv_filter.can_id = 0x42A;
     gwj->can_rcv_filter.can_mask = 0; /* allow all frames */
     /*
      * Depending on routing direction: register at source device
      */
     if (gwj->src.dev->type == ARPHRD_CAN &&
         ce_gw_is_registered_dev(gwj->dst.dev) == 0) {
         /*      && gwj->dst.dev->type == ARPHRD_ETHER) {*/
         /* CAN source --> ETH destination (cegw virtual dev) */
         err = ce_gw_register_can_src(gwj);
     } else if (ce_gw_is_registered_dev(gwj->src.dev) == 0 &&
                gwj->dst.dev->type == ARPHRD_CAN) {
         /* ETH source (cegw virtual dev) --> CAN destination */
         err = ce_gw_register_eth_src(gwj);
     } else {
         /* Undefined routing setup */
         goto clean_exit;
     }
     if (!err)
         hlist_add_head_rcu(&gwj->list, &ce_gw_job_list);
 clean_exit:
     if (err) {
         printk(KERN_ERR "ce_gw: Src or dst device not found or "
                "not compatible (CAN<->CEGW ETH), exit.\n");
         if (gwj->src.dev)
             dev_put(gwj->src.dev);
         if (gwj->dst.dev)
             dev_put(gwj->dst.dev);
         kmem_cache_free(ce_gw_job_cache, gwj);
     }
     return err;
 }
struct canfd_frame* ce_gw_get_header_canfd (canid_t id, __u8 len, __u8 flags, __u8 res0, __u8 res1, __u8 * data) read
Definition at line 200 of file ce_gw_main.c.
References ce_gw_alloc_canfd_frame().
{
     struct canfd_frame *canfd = ce_gw_alloc_canfd_frame();
     if (canfd == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_get_header_canfd\n");
         return NULL;
     }
     canfd->can_id = id;
     canfd->len = len;
     canfd->flags = flags;
     canfd->__res0 = res0;
     canfd->__res1 = res1;
     *(u64 *)canfd->data = *(u64 *)data;
     return canfd;
 }
struct hlist_head* ce_gw_get_job_list (void) read
getter for HLIST_HEAD(ce_gw_job_list)
Returns
Pointer to ce_gw_job_list.
Definition at line 156 of file ce_gw_main.c.
Referenced by ce_gw_netlink_list().
{
     return &ce_gw_job_list;
 }
int ce_gw_remove_route (u32 id)
Definition at line 975 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_unregister_can_src(), ce_gw_unregister_eth_src(), ce_gw_job::dev, ce_gw_job::dst, ce_gw_job::id, ce_gw_job::list, and ce_gw_job::src.
Referenced by ce_gw_cleanup(), ce_gw_dev_unregister(), and ce_gw_netlink_del().
 {
     pr_info("ce_gw: unregister CAN ETH GW routes\n");
     struct ce_gw_job *gwj = NULL;
     struct hlist_node *n, *nx;
     hlist_for_each_entry_safe(gwj, n, nx, &ce_gw_job_list, list) {
         if (gwj->id != id && id)
             continue;
         pr_debug("Removing routing src device: %s, id %x, mask %x\n",
                  gwj->src.dev->name, gwj->can_rcv_filter.can_id,
                  gwj->can_rcv_filter.can_mask);
         hlist_del(&gwj->list);
         /* TODO: Unregister destination device (only for cegw eth) */
         if (gwj->src.dev->type == ARPHRD_CAN)
             ce_gw_unregister_can_src(gwj);
         else
             ce_gw_unregister_eth_src(gwj);
         dev_put(gwj->src.dev);
         dev_put(gwj->dst.dev);
         kmem_cache_free(ce_gw_job_cache, gwj);
     }
     return 0; /* TODO: error, when no suitable entry was found */
 }