can_eth_gw Gateway Module: ce_gw_main.c File Reference
ce_gw_main.c File Reference
Core
Control Area Network - Ethernet - Gateway - Device.
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/list.h>
#include <linux/types.h>
#include <linux/skbuff.h>
#include "ce_gw_dev.h"
#include "ce_gw_netlink.h"
#include <uapi/linux/can.h>
#include <uapi/linux/if_arp.h>
#include <linux/can/core.h>
#include <linux/can/error.h>
#include <linux/slab.h>
#include <linux/if_ether.h>
#include <linux/netdevice.h>
#include <linux/crc32.h>
#include "ce_gw_main.h"
#include <net/ip.h>
#include <asm-generic/errno-base.h>
#include <asm-generic/errno.h>
#include <linux/can/dev.h>
static struct kmem_cache
*ce_gw_job_cache __read_mostly
static int job_count = 1
MODULE_DESCRIPTION ("Control Area Network - Ethernet - Gateway")
MODULE_LICENSE ("GPL")
MODULE_AUTHOR ("Fabian Raab <fabian.raab@tum.de>, ""Stefan Smarzly <stefan.smarzly@in.tum.de>")
MODULE_ALIAS ("can_eth_gateway")
HLIST_HEAD (ce_gw_job_list)
static void list_jobs ()
Some helper tools for testing.
static void test_send_can_to_eth (struct net_device *ethdev)
Keep these files only during development.
static void test_get_vcan_netdev (void)
Keep these files only during development.
static void test_hash_list (void)
Keep these files only during development.
struct hlist_head * ce_gw_get_job_list (void)
getter for HLIST_HEAD(ce_gw_job_list)
struct can_frame * ce_gw_alloc_can_frame (void)
allocates memory for the can frame
void ce_gw_free_can_frame (struct can_frame *memory)
frees memory allocated for can_frame
struct canfd_frame * ce_gw_alloc_canfd_frame (void)
allocates memory for a canfd frame
void ce_gw_free_canfd_frame (struct canfd_frame *memory)
frees memory allocated for can_frame
struct can_frame * ce_gw_get_header_can (canid_t can_id, __u8 can_dlc, __u8 *payload)
builds a can header in SFF (standart frame format) or EFF (extended frame formate) with the given information
struct canfd_frame * ce_gw_get_header_canfd (canid_t id, __u8 len, __u8 flags, __u8 res0, __u8 res1, __u8 *data)
void ce_gw_can2net (struct sk_buff *eth_skb, struct sk_buff *can_skb, struct net_device *eth_dev, struct net_device *can_dev, unsigned char *mac_dst, unsigned char *mac_src)
for CE_GW_TYPE_NET: copy CAN-Frame into ethernet payload
struct sk_buff * ce_gw_can2net_alloc (struct sk_buff *can_skb, struct net_device *eth_dev, struct net_device *can_dev, unsigned char *mac_dst, unsigned char *mac_src)
for CE_GW_TYPE_NET: copy CAN-Frame into ethernet payload and allocate
struct sk_buff * ce_gw_net2can_alloc (struct sk_buff *eth_skb, struct net_device *can_dev)
for CE_GW_TYPE_NET: Copy the can-frame from eth_skb to a new can skb.
void ce_gw_canfd2net (struct sk_buff *eth_skb, struct sk_buff *can_skb, struct net_device *eth_dev, struct net_device *can_dev, unsigned char *mac_dst, unsigned char *mac_src)
for CE_GW_TYPE_NET: copy CAN-Frame into ethernet payload
struct sk_buff * ce_gw_canfd2net_alloc (struct sk_buff *can_skb, struct net_device *eth_dev, struct net_device *can_dev, unsigned char *mac_dst, unsigned char *mac_src)
for CE_GW_TYPE_NET: copy canfd-Frame into ethernet payload and allocate
struct sk_buff * ce_gw_net2canfd_alloc (struct sk_buff *eth_skb, struct net_device *can_dev, struct net_device *eth_dev)
for CE_GW_TYPE_NET: Copy the canfd-frame from eth_skb to a new can skb.
struct sk_buff * ce_gw_can_to_eth (unsigned char *dest, unsigned char *source, __be16 type, struct sk_buff *can_buffer, struct net_device *dev)
converts sk buffer including can frame into sk buffer including ethernet_frame
struct sk_buff * ce_gw_canfd_to_eth (unsigned char *dest, unsigned char *source, __be16 type, struct sk_buff *canfd_skb, struct net_device *dev)
converts sk buffer including canfd frame into sk buffer including ethernet frame
struct sk_buff * ce_gw_eth_to_can (canid_t id, struct sk_buff *eth_buff, struct net_device *dev)
converst sk_buffer including an ethernet frame to sk_buffer including a can_frame
struct sk_buff * ce_gw_eth_to_canfd (canid_t id, __u8 flags, __u8 res0, __u8 res1, struct sk_buff *eth_skb, struct net_device *dev)
converst sk buffer including an ethernet frame to sk buffer including a canfd frame
static __u8 get_ip_version (void *payload)
Reads the first 4 bytes of IP-Header and detects the version.
void ce_gw_can_rcv (struct sk_buff *can_skb, void *data)
The gateway function for incoming CAN frames Receive CAN frame –> process –> send to ETH dev (skbuffer, struct receiver->data)
void ce_gw_eth_rcv (struct sk_buff *eth_skb, void *data)
The gateway function for incoming ETH frames Receive skb from ETH dev –> process –> send to CAN bus.
static int ce_gw_register_can_src (struct ce_gw_job *gwj)
static void ce_gw_unregister_can_src (struct ce_gw_job *gwj)
static int ce_gw_register_eth_src (struct ce_gw_job *gwj)
static void ce_gw_unregister_eth_src (struct ce_gw_job *gwj)
int ce_gw_create_route (int src_ifindex, int dst_ifindex, enum ce_gw_type rt_type, u32 flags)
int ce_gw_remove_route (u32 id)
static int __init ce_gw_init_module (void)
Will be automatic called at module init.
static void __exit ce_gw_cleanup (void)
Will be automatically called on module remove.
module_init (ce_gw_init_module)
module_exit (ce_gw_cleanup)
Detailed Description
Control Area Network - Ethernet - Gateway - Device.
Author
Stefan Smarzly (stefa.nosp@m.n.sm.nosp@m.arzly.nosp@m.@in..nosp@m.tum.d.nosp@m.e)
Fabian Raab (fabia.nosp@m.n.ra.nosp@m.ab@tu.nosp@m.m.de)
Date
May, 2013
Copyright
GNU Public License v3 or higher
Definition in file ce_gw_main.c.
Function Documentation
int ce_gw_create_route (int src_ifindex, int dst_ifindex, enum ce_gw_type rt_type, u32 flags)
Definition at line 915 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_is_registered_dev(), ce_gw_register_can_src(), ce_gw_register_eth_src(), ce_gw_job::dev, ce_gw_job::dropped_frames, ce_gw_job::dst, ce_gw_job::flags, ce_gw_job::handled_frames, ce_gw_job::id, job_count, ce_gw_job::list, ce_gw_job::src, and ce_gw_job::type.
Referenced by ce_gw_netlink_add().
 {
     int err = 0;
     struct ce_gw_job *gwj;
     gwj = kmem_cache_alloc(ce_gw_job_cache, GFP_KERNEL);
     gwj->id = job_count++;
     gwj->handled_frames = 0;
     gwj->dropped_frames = 0;
     err = -ENODEV;
     gwj->src.dev = dev_get_by_index(&init_net, src_ifindex);
     gwj->dst.dev = dev_get_by_index(&init_net, dst_ifindex);
     if (!gwj->src.dev || !gwj->dst.dev)
         goto clean_exit;
     gwj->type = rt_type;
     gwj->flags = flags;
     /* TEST: pre-filled values */
     gwj->can_rcv_filter.can_id = 0x42A;
     gwj->can_rcv_filter.can_mask = 0; /* allow all frames */
     /*
      * Depending on routing direction: register at source device
      */
     if (gwj->src.dev->type == ARPHRD_CAN &&
         ce_gw_is_registered_dev(gwj->dst.dev) == 0) {
         /*      && gwj->dst.dev->type == ARPHRD_ETHER) {*/
         /* CAN source --> ETH destination (cegw virtual dev) */
         err = ce_gw_register_can_src(gwj);
     } else if (ce_gw_is_registered_dev(gwj->src.dev) == 0 &&
                gwj->dst.dev->type == ARPHRD_CAN) {
         /* ETH source (cegw virtual dev) --> CAN destination */
         err = ce_gw_register_eth_src(gwj);
     } else {
         /* Undefined routing setup */
         goto clean_exit;
     }
     if (!err)
         hlist_add_head_rcu(&gwj->list, &ce_gw_job_list);
 clean_exit:
     if (err) {
         printk(KERN_ERR "ce_gw: Src or dst device not found or "
                "not compatible (CAN<->CEGW ETH), exit.\n");
         if (gwj->src.dev)
             dev_put(gwj->src.dev);
         if (gwj->dst.dev)
             dev_put(gwj->dst.dev);
         kmem_cache_free(ce_gw_job_cache, gwj);
     }
     return err;
 }
struct canfd_frame* ce_gw_get_header_canfd (canid_t id, __u8 len, __u8 flags, __u8 res0, __u8 res1, __u8 * data) read
Definition at line 200 of file ce_gw_main.c.
References ce_gw_alloc_canfd_frame().
{
     struct canfd_frame *canfd = ce_gw_alloc_canfd_frame();
     if (canfd == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_get_header_canfd\n");
         return NULL;
     }
     canfd->can_id = id;
     canfd->len = len;
     canfd->flags = flags;
     canfd->__res0 = res0;
     canfd->__res1 = res1;
     *(u64 *)canfd->data = *(u64 *)data;
     return canfd;
 }
struct hlist_head * ce_gw_get_job_list (void) read
getter for HLIST_HEAD(ce_gw_job_list)
Returns
Pointer to ce_gw_job_list.
Definition at line 156 of file ce_gw_main.c.
Referenced by ce_gw_netlink_list().
{
     return &ce_gw_job_list;
 }
static int ce_gw_register_can_src (struct ce_gw_job * gwj) inline static
Definition at line 887 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_can_rcv(), ce_gw_job::dev, and ce_gw_job::src.
Referenced by ce_gw_create_route().
 {
     return can_rx_register(gwj->src.dev, gwj->can_rcv_filter.can_id,
                            gwj->can_rcv_filter.can_mask, ce_gw_can_rcv,
                            gwj, "ce_gw");
 }
static int ce_gw_register_eth_src (struct ce_gw_job * gwj) inline static
Definition at line 902 of file ce_gw_main.c.
References ce_gw_dev_job_src_add().
Referenced by ce_gw_create_route().
 {
     ce_gw_dev_job_src_add(gwj);
     return 0;
 }
int ce_gw_remove_route (u32 id)
Definition at line 975 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_unregister_can_src(), ce_gw_unregister_eth_src(), ce_gw_job::dev, ce_gw_job::dst, ce_gw_job::id, ce_gw_job::list, and ce_gw_job::src.
Referenced by ce_gw_cleanup(), ce_gw_dev_unregister(), and ce_gw_netlink_del().
 {
     pr_info("ce_gw: unregister CAN ETH GW routes\n");
     struct ce_gw_job *gwj = NULL;
     struct hlist_node *n, *nx;
     hlist_for_each_entry_safe(gwj, n, nx, &ce_gw_job_list, list) {
         if (gwj->id != id && id)
             continue;
         pr_debug("Removing routing src device: %s, id %x, mask %x\n",
                  gwj->src.dev->name, gwj->can_rcv_filter.can_id,
                  gwj->can_rcv_filter.can_mask);
         hlist_del(&gwj->list);
         /* TODO: Unregister destination device (only for cegw eth) */
         if (gwj->src.dev->type == ARPHRD_CAN)
             ce_gw_unregister_can_src(gwj);
         else
             ce_gw_unregister_eth_src(gwj);
         dev_put(gwj->src.dev);
         dev_put(gwj->dst.dev);
         kmem_cache_free(ce_gw_job_cache, gwj);
     }
     return 0; /* TODO: error, when no suitable entry was found */
 }
static void ce_gw_unregister_can_src (struct ce_gw_job * gwj) inline static
Definition at line 894 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_can_rcv(), ce_gw_job::dev, and ce_gw_job::src.
Referenced by ce_gw_remove_route().
 {
     return can_rx_unregister(gwj->src.dev, gwj->can_rcv_filter.can_id,
                              gwj->can_rcv_filter.can_mask,
                              ce_gw_can_rcv, gwj);
 }
static void ce_gw_unregister_eth_src (struct ce_gw_job * gwj) inline static
Definition at line 909 of file ce_gw_main.c.
References ce_gw_dev_job_remove().
Referenced by ce_gw_remove_route().
 {
     ce_gw_dev_job_remove(gwj);
 }
HLIST_HEAD (ce_gw_job_list)
static void list_jobs (void) static
Some helper tools for testing.
Definition at line 1062 of file ce_gw_main.c.
References ce_gw_job::dev, ce_gw_job::dst, ce_gw_job::id, and ce_gw_job::src.
Referenced by ce_gw_init_module().
 {
     struct ce_gw_job *gwj = NULL;
     struct hlist_node *n, *nx;
     pr_info("Routing jobs\n"
             "------------\n");
     hlist_for_each_entry_safe(gwj, n, nx, &ce_gw_job_list, list) {
         pr_info("ID: %i, input dev: %s, output dev: %s\n",
                 gwj->id, gwj->src.dev->name, gwj->dst.dev->name);
     }
     if (!gwj)
         pr_info("No ce_gw routing jobs found!\n");
 }
MODULE_ALIAS ("can_eth_gateway")
MODULE_AUTHOR ("Fabian Raab <fabian.raab@tum.de> , ""Stefan Smarzly< stefan.smarzly @in.tum.de >")
MODULE_DESCRIPTION ("Control Area Network - Ethernet - Gateway")
 _______________________________________________________
|                                                       |
|       CAN Ethernet Gateway Kernel Module (ce_gw)      |
|_______________________________________________________|
|                                                       |
|           Ethernet Frame    +----------------------+  |  CAN Frame
|           +-----o---------->|CAN - Ethernet Gateway|<-+-------o----+
|           |                 |     ce_gw_main.c     |  |            |
|           |                 +----------------------+  |            v
|           v                                           |       +----------+
| +--------------------+                                |       |CAN Device|
| |virtual Ethernet dev|                                |       |  can.c   |
| |('cegw#' Interface) |         +---------------+      |       +----------+
| |    ce_gw_dev.c     |         |Netlink Server |      |            ^
| +--------------------+         |ce_gw_netlink.c|      |            |
|           ^                    +---------------+      |            v
|           |                            ^              |       +----------+
|___________|____________________________|______________|       |CAN Driver|
            |                            o Netlink Frame        +----------+
            v            Kernelspace     |                           ^
          +----+       __________________|_____________              |
          | OS |         Userspace       |                           v
          +----+                         v                       +-------+
                                +------------------+             |CAN NIC|
                                |  Netlink Client  |             +-------+
                                |    netlink.c     |
                                |(can-eth-gw-utils)|
                                +------------------+
Diagramm witch shows the relation and Packet transmission between the components of this kernel module (ce_gw) and others of the OS.
    +------------------+             /--------------------------------------\
    |   <<Ethernet>>   |             |ce_gw_job has Ethernet as dest and CAN|
    |struct net_device |             |as source OR has Ethernet as src and  |
    +------------------+             |CAN as dst. hlist_node annotations are|
+-->|       ....       |             |Members of the structs where the arrow|
|   +------------------+             |points to. The hlist structs are not  |
|           |                        |directly represented here and are so  |
|           |void *priv              |simplyfied.                           |
|           |                        \--------------------------------------/
|           v
|   +---------------------+        struct hlist_head ce_gw_job_list
|   |struct ce_gw_job_info|                       |
|   +---------------------+                       |
|   |                     |    struct hlist_node  |
|   +---------------------+        list         \ |
|                 | | struct                     \|
|         struct  | |hlist_head                   |     +------------------+
|       hlist_head| | job_src                     |     |     <<CAN>>      |
|         job_dst | |                             |     |struct net_device |
|                 | |\                            |     +------------------+
|                 | | struct hlist_node           |     |       ....       |
|                 | |/   list_dev                 |     +------------------+
|                 | /                             |               ^
|                 |/|                             |0...*          |
| struct          | |       0...*                 v               | struct
|net_device       | +--------->+----------------------+           |net_device
| *dev            +----------->|  struct ce_gw_job    |           | *dev
|                        0...* +----------------------+           |
|        +-------------+       |struct rcu_head rcu   |      +-------------+
|        |   union     |       |u32 id                |      |   union     |
+--------+-------------+       |enum ce_gw_type type  |      +-------------+
         |             |<>-----|u32 flags             |----<>|             |
         +-------------+  dst/ |u32 handled_frames    | src/ +-------------+
                          src  |u32 dropped_frames    | dst
                               |union { struct can_   |
                               |filter can_rcv_filter}|
                               +----------------------+
This is an UML Klass Diagramm witch shows the main routing Management lists.
module_exit (ce_gw_cleanup)
module_init (ce_gw_init_module)
MODULE_LICENSE ("GPL")
static void test_get_vcan_netdev (void) static
Keep these files only during development.
Definition at line 1093 of file ce_gw_main.c.
 {
     struct net_device *dev;
     char vcandev[] = "vcan1";
     pr_debug("cegw testing: Try finding vcan0 net_device.\n");
     /* use dev_get_by_index for ifindex */
     if ((dev = __dev_get_by_name(&init_net, vcandev)) == NULL) {
         pr_debug("cegw testing: %s not found.\n", vcandev);
         return;
     }
     /* Getting infos from vcan device */
     pr_debug("cegw testing: %s found!\n", vcandev);
     pr_debug("type: %i, ifindex: %i\n", dev->type, dev->ifindex);
 }
static void test_hash_list (void) static
Keep these files only during development.
Definition at line 1113 of file ce_gw_main.c.
References ce_gw_job::dropped_frames, and ce_gw_job::list.
 {
     struct ce_gw_job *gwj1 = kmem_cache_alloc(ce_gw_job_cache, GFP_KERNEL);
     gwj1->dropped_frames = 25;
     struct ce_gw_job *gwj2 = kmem_cache_alloc(ce_gw_job_cache, GFP_KERNEL);
     gwj2->dropped_frames = 250;
     /* dynamic alloc, dangerous when out of scope*/
     struct ce_gw_job gwj3 = {
         .dropped_frames = 555
     };
     hlist_add_head(&gwj1->list, &ce_gw_job_list);
     hlist_add_head(&gwj2->list, &ce_gw_job_list);
     hlist_add_head(&gwj3.list, &ce_gw_job_list);
     struct ce_gw_job *gwj = NULL;
     struct hlist_node *n, *nx;
     hlist_for_each_entry(gwj, n, &ce_gw_job_list, list) {
         pr_debug("cegw hashtest: List entry %i\n", gwj->dropped_frames);
     }
 }
static void test_send_can_to_eth (struct net_device * ethdev) static
Keep these files only during development.
Definition at line 1080 of file ce_gw_main.c.
 {
     struct sk_buff *skb;
     skb = netdev_alloc_skb(ethdev, sizeof(struct ethhdr) +
                            sizeof(struct can_frame));
     skb_reserve(skb, sizeof(struct ethhdr));
 }
Variable Documentation
struct kmem_cache* ce_gw_job_cache __read_mostly static
Definition at line 147 of file ce_gw_main.c.
int job_count = 1 static
Definition at line 148 of file ce_gw_main.c.
Referenced by ce_gw_create_route().