can_eth_gw Gateway Module: ce_gw_dev.c File Reference
ce_gw_dev.c File Reference
Core
Control Area Network - Ethernet - Gateway - Device.
#include <linux/version.h>
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/list.h>
#include <linux/netdevice.h>
#include <linux/etherdevice.h>
#include <uapi/linux/can.h>
#include "ce_gw_dev.h"
#include "ce_gw_main.h"
#include <asm-generic/errno-base.h>
#include <asm-generic/errno.h>
Data Structures
struct ce_gw_dev_list
internal list of all registered and allocated devices.
static struct kmem_cache
*ce_gw_dev_cache __read_mostly
static struct net_device_ops ce_gw_ops
Defined Functions of Ethernet device.
HLIST_HEAD (ce_gw_dev_allocated)
HLIST_HEAD (ce_gw_dev_registered)
int ce_gw_dev_open (struct net_device *dev)
called by the OS on device up
int ce_gw_dev_stop (struct net_device *dev)
called by the OS on device down
static int ce_gw_dev_start_xmit (struct sk_buff *skb, struct net_device *dev)
called by the OS if a package is sent to the device
int ce_gw_dev_init (struct net_device *dev)
called by the OS on device registered
int ce_gw_is_allocated_dev (struct net_device *eth_dev)
check if the param eth_dev is allocated by this module
int ce_gw_is_registered_dev (struct net_device *eth_dev)
check if the param eth_dev is registered by this module
int ce_gw_has_min_mtu (struct net_device *dev, enum ce_gw_type type, u32 flags)
checks if the given device has enough mtu to use the type and flags
void ce_gw_dev_job_src_add (struct ce_gw_job *job)
Adds an pointer to the net_device internal list where it is the src.
void ce_gw_dev_job_dst_add (struct ce_gw_job *job)
Adds an pointer to the net_device internal list where it is the dst.
int ce_gw_dev_job_add (struct net_device *eth_dev, struct ce_gw_job *job)
Adds an pointer to the net_device internal list where it is part of.
void ce_gw_dev_job_remove (struct ce_gw_job *job)
Removes the pointer to param job from the list in ethernet net_device.
struct net_device * ce_gw_dev_alloc (char *dev_name)
void ce_gw_dev_free (struct net_device *eth_dev)
Free virtual ethernet device and remove from internal lists.
void ce_gw_dev_setup (struct net_device *dev, enum ce_gw_type type, __u32 flags)
Sets the default attributes for the Gateway Ethernet device.
struct net_device * ce_gw_dev_create (enum ce_gw_type type, __u32 flags, char *dev_name)
int ce_gw_dev_register (struct net_device *eth_dev)
Register a virtual ethernet device on the OS.
void ce_gw_dev_unregister (struct net_device *eth_dev)
Unregister virtual ethernet device and remove from internal lists.
int ce_gw_dev_init_module (void)
Initialise all objects, wich are needed by the other functions.
void ce_gw_dev_cleanup (void)
Deleting all objects created by ce_gw_dev_init_module() and all devices.
Detailed Description
Control Area Network - Ethernet - Gateway - Device.
Author
Fabian Raab (fabia.nosp@m.n.ra.nosp@m.ab@tu.nosp@m.m.de)
Date
May, 2013
Copyright
GNU Public License v3 or higher
Definition in file ce_gw_dev.c.
Function Documentation
struct net_device* ce_gw_dev_alloc (char * dev_name) read
Definition at line 279 of file ce_gw_dev.c.
References ce_gw_dev_list::dev, ce_gw_job_info::job_dst, ce_gw_job_info::job_src, and ce_gw_dev_list::list_alloc.
Referenced by ce_gw_dev_create().
{
     pr_debug("ce_gw_dev: Alloc Device\n");
     struct net_device *dev;
     dev = alloc_netdev(sizeof(struct ce_gw_job_info),
                        dev_name, ether_setup);
     if (dev == NULL) {
         pr_err("ce_gw_dev: Error allocation etherdev.");
         goto ce_gw_dev_create_error;
     }
     /* initialize private field */
     struct ce_gw_job_info *priv = netdev_priv(dev);
     memset(priv, 0, sizeof(struct ce_gw_job_info));
     priv->job_src.first = NULL;
     priv->job_dst.first = NULL;
     /* create list entry and add */
     struct ce_gw_dev_list *dl;
     dl = kmem_cache_alloc(ce_gw_dev_cache, GFP_KERNEL);
     if (dl == NULL) {
         pr_err("ce_gw_dev: cache alloc failed");
         goto ce_gw_dev_create_error_cache;
     }
     dl->dev = dev;
     hlist_add_head_rcu(&dl->list_alloc, &ce_gw_dev_allocated);
     return dev;
 ce_gw_dev_create_error_cache:
     kmem_cache_free(ce_gw_dev_cache, dl);
 ce_gw_dev_create_error:
     free_netdev(dev);
     return NULL;
 }
struct net_device* ce_gw_dev_create (enum ce_gw_type type, __u32 flags, char * dev_name) read
Definition at line 381 of file ce_gw_dev.c.
References ce_gw_dev_alloc(), and ce_gw_dev_setup().
Referenced by ce_gw_netlink_add().
                      {
     struct net_device *dev;
     dev = ce_gw_dev_alloc(dev_name);
     ce_gw_dev_setup(dev, type, flags);
     return dev;
 }
int ce_gw_has_min_mtu (struct net_device * dev, enum ce_gw_type type, u32 flags)
checks if the given device has enough mtu to use the type and flags
Parameters
dev The net_device which schould be checked
type The type which sould be compared to
flags needed dor the CE_GW_F_CAN_FD flag, to check if the type is CANfd capable
Return values
true The mtu of dev is bigger then the nedded mtu by the type
false if not
Definition at line 213 of file ce_gw_dev.c.
References CE_GW_F_CAN_FD, CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_NONE, CE_GW_TYPE_TCP, and CE_GW_TYPE_UDP.
Referenced by ce_gw_create_route().
{
     int mtu = ETH_DATA_LEN; /* Standart Ethernet Value */
     switch (type) {
     case CE_GW_TYPE_NONE:
         /* Do Nothing (default Ethernet MTU will be set) */
         break;
     case CE_GW_TYPE_ETH:
         if ((flags & CE_GW_F_CAN_FD) == CE_GW_F_CAN_FD) {
             mtu = CANFD_MAX_DLEN;
         } else {
             mtu = CAN_MAX_DLEN;
         }
         break;
     case CE_GW_TYPE_NET:
         if ((flags & CE_GW_F_CAN_FD) == CE_GW_F_CAN_FD) {
             mtu = sizeof(struct canfd_frame);
         } else {
             mtu = sizeof(struct can_frame);
         }
         break;
     case CE_GW_TYPE_TCP:
         /* TODO nothing yet */
         break;
     case CE_GW_TYPE_UDP:
         /* TODO nothing yet */
         break;
     default:
         pr_err("ce_gw_dev: Type not defined.");
     }
     if (dev->mtu >= mtu) {
         return true;
     }
     return false;
 }
HLIST_HEAD (ce_gw_dev_allocated)
list of all allocated ethernet devices
HLIST_HEAD (ce_gw_dev_registered)
list of all registered ethernet devices
Variable Documentation
struct kmem_cache* ce_gw_dev_cache __read_mostly static
cache for lists
Definition at line 54 of file ce_gw_dev.c.
struct net_device_ops ce_gw_ops static
Initial value:
= {
    .ndo_init   = ce_gw_dev_init,
    .ndo_open   = ce_gw_dev_open,
    .ndo_stop   = ce_gw_dev_stop,
    .ndo_start_xmit = ce_gw_dev_start_xmit,
    0
}
Defined Functions of Ethernet device.
Definition at line 164 of file ce_gw_dev.c.
Referenced by ce_gw_dev_setup().