can_eth_gw Gateway Module: Flags
Flags
Data Structures
struct ce_gw_job
Variables
struct hlist_node list
struct rcu_head rcu
struct hlist_node list_dev
u32 id
enum ce_gw_type type
u32 flags
u32 handled_frames
u32 dropped_frames
struct net_device * dev
union {
struct net_device * dev
} src
struct net_device * dev
union {
struct net_device * dev
} dst
struct can_filter can_rcv_filter
union {
struct can_filter can_rcv_filter
};
#define CE_GW_F_CAN_FD 0x00000001
#define CE_GW_F_Test 0x00000002
Constants
enum ce_gw_type {
CE_GW_TYPE_NONE, CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_TCP,
CE_GW_TYPE_UDP, __CE_GW_TYPE_MAX
}
struct hlist_head * ce_gw_get_job_list (void)
getter for HLIST_HEAD(ce_gw_job_list)
struct can_frame * ce_gw_alloc_can_frame (void)
allocates memory for the can frame
void ce_gw_free_can_frame (struct can_frame *memory)
frees memory allocated for can_frame
struct canfd_frame * ce_gw_alloc_canfd_frame (void)
allocates memory for a canfd frame
void ce_gw_free_canfd_frame (struct canfd_frame *memory)
frees memory allocated for can_frame
struct can_frame * ce_gw_get_header_can (canid_t can_id, __u8 can_dlc, __u8 *payload)
builds a can header in SFF (standart frame format) or EFF (extended frame formate) with the given information
struct canfd_frame * ce_gw_get_header_canfd (canid_t id, __u8 len, __u8 flags, __u8 res0, __u8 res1, __u8 *data)
struct sk_buff * ce_gw_can_to_eth (unsigned char *dest, unsigned char *source, __be16 type, struct sk_buff *can_buffer, struct net_device *net)
converts sk buffer including can frame into sk buffer including ethernet_frame
struct sk_buff * ce_gw_canfd_to_eth (unsigned char *dest, unsigned char *source, __be16 type, struct sk_buff *canfd_skb, struct net_device *net)
converts sk buffer including canfd frame into sk buffer including ethernet frame
struct sk_buff * ce_gw_eth_to_can (canid_t id, struct sk_buff *eth_buff, struct net_device *net)
converst sk_buffer including an ethernet frame to sk_buffer including a can_frame
struct sk_buff * ce_gw_eth_to_canfd (canid_t id, __u8 flags, __u8 res0, __u8 res1, struct sk_buff *eth_skb, struct net_device *net)
converst sk buffer including an ethernet frame to sk buffer including a canfd frame
void ce_gw_can_rcv (struct sk_buff *can_skb, void *data)
The gateway function for incoming CAN frames Receive CAN frame –> process –> send to ETH dev (skbuffer, struct receiver->data)
void ce_gw_eth_rcv (struct sk_buff *eth_skb, void *data)
The gateway function for incoming ETH frames Receive skb from ETH dev –> process –> send to CAN bus.
int ce_gw_create_route (int src_ifindex, int dst_ifindex, enum ce_gw_type rt_type, u32 flags)
int ce_gw_remove_route (u32 id)
Detailed Description
Flags Definition for struct ce_gw_job->flags
Macro Definition Documentation
#define CE_GW_F_CAN_FD 0x00000001
is Gateway CANfd compatible
Definition at line 53 of file ce_gw_main.h.
#define CE_GW_F_Test 0x00000002
Test flag
Definition at line 54 of file ce_gw_main.h.
Enumeration Type Documentation
enum ce_gw_type
Enumerator
CE_GW_TYPE_NONE
No Type. Should normally not be used.
CE_GW_TYPE_ETH
Convert CAN header to Ethernet header Payload of CAN header must contain an IP header
CE_GW_TYPE_NET
Copy complete CAN Frame into Ethernet payload e.g use CAN as Network Layer (Layer 3) protocol.
CE_GW_TYPE_TCP
Convert CAN header into an IP/TCP package
CE_GW_TYPE_UDP
Convert CAN header into an IP/UDP package
__CE_GW_TYPE_MAX
Maximum Type Number + 1
Definition at line 69 of file ce_gw_main.h.
                 {
     CE_GW_TYPE_NONE,
     CE_GW_TYPE_ETH,
     CE_GW_TYPE_NET,
     CE_GW_TYPE_TCP,
     CE_GW_TYPE_UDP,
     __CE_GW_TYPE_MAX,
 };
Function Documentation
struct can_frame* ce_gw_alloc_can_frame (void) read
allocates memory for the can frame
Returns
pointer to the memory allocated
Todo:
not tested yet
Definition at line 160 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_can(), and ce_gw_get_header_can().
{
     struct can_frame *memory;
     memory = kmalloc(sizeof(struct can_frame),GFP_KERNEL);
     return memory;
 }
struct canfd_frame* ce_gw_alloc_canfd_frame (void) read
allocates memory for a canfd frame
Returns
pointer to the memory allocated
Todo:
not tested yet
Definition at line 172 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_canfd(), and ce_gw_get_header_canfd().
{
     struct canfd_frame *memory;
     memory = kmalloc(sizeof(struct canfd_frame), GFP_KERNEL);
     return memory;
 }
void ce_gw_can_rcv (struct sk_buff * can_skb, void * data)
The gateway function for incoming CAN frames Receive CAN frame –> process –> send to ETH dev (skbuffer, struct receiver->data)
Parameters
can_skb CAN sk buffer which should be translated to an ETH packet
data gwjob which is responsible for triggering this function
Todo:
check also for canfd flag not only Type and call function. You must also check then if the message then is really a canfd-frame or not.
call other translation functions. check for canfd-frame or only use canfd-frame casts.
Definition at line 758 of file ce_gw_main.c.
References ce_gw_can2net_alloc(), CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_TCP, CE_GW_TYPE_UDP, ce_gw_job::dev, ce_gw_job::dropped_frames, ce_gw_job::dst, ce_gw_job::handled_frames, ce_gw_job::src, and ce_gw_job::type.
Referenced by ce_gw_register_can_src(), and ce_gw_unregister_can_src().
 {
     int err = 0;
     struct can_frame *cf;
     /* CAN frame (id, dlc, data)*/
     cf = (struct can_frame *)can_skb->data;
     pr_debug("Incoming msg from can dev: can_id %x, len %i, can_msg %x\n",
              cf->can_id, cf->can_dlc, cf->data[0]);
     struct ce_gw_job *cgj = (struct ce_gw_job *)data;
     struct sk_buff *eth_skb = NULL;
     long int dmac = 0xffffffffffff;
     long int smac = 0x000000000000;
     switch (cgj->type) {
     case CE_GW_TYPE_ETH:
         pr_info("Translation ETH not implemented yet.");
         break;
     case CE_GW_TYPE_NET:
         eth_skb = ce_gw_can2net_alloc(can_skb,
                                       cgj->dst.dev,
                                       cgj->src.dev,
                                       (unsigned char *) &dmac,
                                       (unsigned char *) &smac);
         break;
     case CE_GW_TYPE_TCP:
         pr_info("Translation IP TCP not implemented yet.");
         break;
     case CE_GW_TYPE_UDP:
         pr_info("Translation IP UDP not implemented yet.");
         break;
     default:
         pr_err("ce_gw: Translation type of ce_gw_job not "
                "implemented. BUG: Some module inserted an invalid "
                "type. Use enum ce_gw_type instead.");
         goto drop_frame;
         break;
     }
     err = netif_rx_ni(eth_skb);
     if (err != 0) {
         pr_err("ce_gw: send to kernel failed");
         cgj->dropped_frames++;
         goto exit_error;
     }
     cgj->handled_frames++;
     /* TODO If you use kfree_skb(can_skb) the system hang up completely
      * without printing stack trace. But a few packets normally passed
      * before sytem hang up. But <linux/can/dev.h> uses kfree_skb(). There
      * is no refdata count left. The reason why hang up is completely
      * unknown. */
 exit_error:
     pr_info("ce_gw: WARNING can skb will not be freed");
     /*kfree_skb(can_skb);*/
     return;
 drop_frame:
     cgj->dropped_frames++;
     dev_kfree_skb(eth_skb);
     return;
 }
struct sk_buff* ce_gw_can_to_eth (unsigned char * dest, unsigned char * source, __be16 type, struct sk_buff * can_buffer, struct net_device * dev) read
converts sk buffer including can frame into sk buffer including ethernet_frame
Parameters
dest MAC address of destination
source MAC address of source
type type of layer3 message (example: ipv4 or ipv6 ...)
can_buffer sk buffer including a can frame
dev device of destination
Return values
sk_buffer on success including ethernet frame
NULL if unsuccessful
Todo:
not tested yet
Definition at line 532 of file ce_gw_main.c.
{
     struct can_frame *can_frame_skb = (struct can_frame *)
                                       can_buffer->data;
     struct ethhdr *ethhdr;
     u8 canlen = can_dlc2len(can_frame_skb->can_dlc);
     struct sk_buff *eth_skb = dev_alloc_skb(sizeof(struct ethhdr) + sizeof
                                             (struct can_frame) + 64);
     if (eth_skb == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_can_to_eth \n");
         return NULL;
     }
     eth_skb->dev = dev;
     /*updates data pointer to tail */
     skb_reserve(eth_skb, sizeof(struct ethhdr) + sizeof(struct can_frame) +
                 64);
     /*updates data pointer to start of network header*/
     eth_skb->data = skb_push(eth_skb, (const int) canlen);
     /*copys data from can sk buffer into ethernet sk buffer */
     memcpy(eth_skb->data, can_buffer->data + sizeof(struct can_frame) -
            - canlen, canlen);
     /*update network_header */
     skb_set_network_header(eth_skb, 0);
     /*updates transport header */
     skb_set_transport_header(eth_skb, (const int) canlen);
     /*updates data pointer to mac header */
     eth_skb->data = skb_push(eth_skb, (const int) sizeof(struct ethhdr));
     /*updates mac_header*/
     skb_set_mac_header(eth_skb, 0);
     /*fills ethhdr with data */
     ethhdr = eth_hdr(eth_skb);
     memcpy(ethhdr->h_dest, dest, ETH_ALEN);
     memcpy(ethhdr->h_source, source, ETH_ALEN);
     ethhdr->h_proto = type;
     return eth_skb;
 }
struct sk_buff* ce_gw_canfd_to_eth (unsigned char * dest, unsigned char * source, __be16 type, struct sk_buff * canfd_skb, struct net_device * dev) read
converts sk buffer including canfd frame into sk buffer including ethernet frame
Parameters
dest MAC address of destination
source MAC address of source
type type of layer3 message (example: ipv4 or ipv6 ...)
canfd_skb sk buffer including a canfd_frame
dev device of the destination
Return values
sk_buff including ethernet frame if successful
NULL if unsuccessful
Todo:
not tested yet
Definition at line 576 of file ce_gw_main.c.
{
     struct sk_buff *eth_skb = dev_alloc_skb(sizeof(struct ethhdr) +
                                             sizeof(struct canfd_frame) + 64);
     if (eth_skb == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_canfd_to_eth \n");
         return NULL;
     }
     struct ethhdr *ethhdr;
     struct canfd_frame *canfd_frame_skb = (struct canfd_frame *)
                                           canfd_skb->data;
     u8 canlen = can_dlc2len(canfd_frame_skb->len);
     unsigned int iplen = ip_hdrlen(canfd_skb);
     eth_skb->dev = dev;
     /*updates data pointer to tail */
     skb_reserve(eth_skb, sizeof(struct ethhdr) + sizeof(struct canfd_frame)
                 + 64);
     /*updates data pointer to start of network header*/
     eth_skb->data = skb_push(eth_skb, (const int) canlen);
     /*copys data from canfd sk buffer into ethernet sk buffer */
     memcpy(eth_skb->data, canfd_skb->data + sizeof(struct canfd_frame) -
            sizeof(__u8)*64, canlen);
     /*update network_header */
     skb_set_network_header(eth_skb, 0);
     /*updates transport header */
     if (canlen >= iplen) {
         skb_set_transport_header(eth_skb, (const int) iplen);
     } else {
         skb_set_transport_header(eth_skb, (const int) sizeof(__u8)*64);
     }
     /*updates data pointer to start of mac header*/
     eth_skb->data = skb_push(eth_skb, (const int) sizeof(struct ethhdr));
     /*updates mac_header*/
     skb_set_mac_header(eth_skb, 0);
     /*fills eth_skb with data*/
     ethhdr = eth_hdr(eth_skb);
     memcpy(ethhdr->h_dest, &dest, ETH_ALEN);
     memcpy(ethhdr->h_source, &source, ETH_ALEN);
     ethhdr->h_proto = type;
     return eth_skb;
 }
int ce_gw_create_route (int src_ifindex, int dst_ifindex, enum ce_gw_type rt_type, u32 flags)
Definition at line 915 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_is_registered_dev(), ce_gw_register_can_src(), ce_gw_register_eth_src(), ce_gw_job::dev, ce_gw_job::dropped_frames, ce_gw_job::dst, ce_gw_job::flags, ce_gw_job::handled_frames, ce_gw_job::id, job_count, ce_gw_job::list, ce_gw_job::src, and ce_gw_job::type.
Referenced by ce_gw_netlink_add().
 {
     int err = 0;
     struct ce_gw_job *gwj;
     gwj = kmem_cache_alloc(ce_gw_job_cache, GFP_KERNEL);
     gwj->id = job_count++;
     gwj->handled_frames = 0;
     gwj->dropped_frames = 0;
     err = -ENODEV;
     gwj->src.dev = dev_get_by_index(&init_net, src_ifindex);
     gwj->dst.dev = dev_get_by_index(&init_net, dst_ifindex);
     if (!gwj->src.dev || !gwj->dst.dev)
         goto clean_exit;
     gwj->type = rt_type;
     gwj->flags = flags;
     /* TEST: pre-filled values */
     gwj->can_rcv_filter.can_id = 0x42A;
     gwj->can_rcv_filter.can_mask = 0; /* allow all frames */
     /*
      * Depending on routing direction: register at source device
      */
     if (gwj->src.dev->type == ARPHRD_CAN &&
         ce_gw_is_registered_dev(gwj->dst.dev) == 0) {
         /*      && gwj->dst.dev->type == ARPHRD_ETHER) {*/
         /* CAN source --> ETH destination (cegw virtual dev) */
         err = ce_gw_register_can_src(gwj);
     } else if (ce_gw_is_registered_dev(gwj->src.dev) == 0 &&
                gwj->dst.dev->type == ARPHRD_CAN) {
         /* ETH source (cegw virtual dev) --> CAN destination */
         err = ce_gw_register_eth_src(gwj);
     } else {
         /* Undefined routing setup */
         goto clean_exit;
     }
     if (!err)
         hlist_add_head_rcu(&gwj->list, &ce_gw_job_list);
 clean_exit:
     if (err) {
         printk(KERN_ERR "ce_gw: Src or dst device not found or "
                "not compatible (CAN<->CEGW ETH), exit.\n");
         if (gwj->src.dev)
             dev_put(gwj->src.dev);
         if (gwj->dst.dev)
             dev_put(gwj->dst.dev);
         kmem_cache_free(ce_gw_job_cache, gwj);
     }
     return err;
 }
void ce_gw_eth_rcv (struct sk_buff * eth_skb, void * data)
The gateway function for incoming ETH frames Receive skb from ETH dev –> process –> send to CAN bus.
Parameters
eth_skb ETH sk buffer with CAN frame as payload. Exact location of CAN frame depends on translation type (see enum ce_gw_type)
data gwjob which is responsible for triggering this function
Todo:
check for canfd-frame or only use canfd-frame casts.
Definition at line 828 of file ce_gw_main.c.
References ce_gw_net2can_alloc(), CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_TCP, CE_GW_TYPE_UDP, ce_gw_job::dev, ce_gw_job::dropped_frames, ce_gw_job::dst, ce_gw_job::handled_frames, ce_gw_job::id, and ce_gw_job::type.
 {
     struct ce_gw_job *gwj = (struct ce_gw_job *)data;
     /* Create Can skb and convert incoming Eth sk buffer depending on
      * type (ce_gw_type in gwj)
      */
     struct sk_buff *can_skb = NULL;
     switch (gwj->type) {
     case CE_GW_TYPE_ETH:
         pr_info("Translation ETH not implemented yet.");
         break;
     case CE_GW_TYPE_NET:
         can_skb = ce_gw_net2can_alloc(eth_skb, gwj->dst.dev);
         break;
     case CE_GW_TYPE_TCP:
         pr_info("Translation IP TCP not implemented yet.");
         break;
     case CE_GW_TYPE_UDP:
         pr_info("Translation IP UDP not implemented yet.");
         break;
     default:
         printk(KERN_ERR "ce_gw: Translation type of ce_gw_job not "
                "implemented. BUG: Some module inserted an invalid "
                "type. Use enum ce_gw_type instead.");
         goto drop_frame;
         break;
     }
     /* Memory allocation or translation ETH -> CAN failed */
     if (!can_skb)
         goto drop_frame;
     struct can_frame *cf;
     cf = (struct can_frame *)can_skb->data;
     pr_debug("Incoming msg from eth dev (gwj %i): "
              "can_id %x, len %i, can_msg(1) %x\n",
              gwj->id, cf->can_id, cf->can_dlc, cf->data[0]);
     /* send to CAN netdevice (with echo flag for loopback devices) */
     if (can_send(can_skb, 0x01))
         goto drop_frame;
     else
         gwj->handled_frames++;
     return; /* Receive + process + send to CAN successful */
 drop_frame:
     gwj->dropped_frames++;
     dev_kfree_skb(can_skb);
     return;
 }
struct sk_buff* ce_gw_eth_to_can (canid_t id, struct sk_buff * eth_buff, struct net_device * dev) read
converst sk_buffer including an ethernet frame to sk_buffer including a can_frame
Parameters
id identifier of can_frame (see ce_gw_get_header for more information
eth_buff sk_buffer including an ethernet frame
dev device of the destination
Returns
sk_buffer including a can frame
Todo:
not tested yet
Definition at line 624 of file ce_gw_main.c.
References ce_gw_alloc_can_frame(), and ce_gw_free_can_frame().
{
     struct sk_buff *can_buff;
     struct can_frame *can = ce_gw_alloc_can_frame();
     if (can == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_eth_to_can \n");
         return NULL;
     }
     unsigned int ethdatalen = (skb_tail_pointer(eth_buff) - (eth_buff->data
                                + sizeof(struct ethhdr)));
     /* unsigned int iplen = ip_hdrlen(eth_buff); */
     /*fills can header */
     can->can_id = id;
     can->can_dlc = (__u8) eth_buff->data_len - sizeof(struct ethhdr);
     can_buff = dev_alloc_skb(sizeof(struct can_frame) + ethdatalen + 64);
     if (can_buff == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_eth_to_can \n");
         return NULL;
     }
     can_buff->dev = dev;
     /*updates data pointer to tail */
     skb_reserve(can_buff, sizeof(struct can_frame) + ethdatalen + 64);
     /*updates data pointer to start of network header*/
     can_buff->data = skb_push(can_buff, (const int) ethdatalen);
     /*copys data from ethernet sk buffer into can buffer */
     memcpy(can_buff->data, eth_buff->data + sizeof(struct ethhdr),
            sizeof(u64));
     /*update network_header */
     skb_set_network_header(can_buff, 0);
     /*updates transport header */
     skb_set_transport_header(can_buff, (const int) sizeof(u64));
     /*updates data pointer to start of mac header */
     can_buff->data = skb_push(can_buff, (const int) sizeof(__u32) +
                               sizeof(__u8));
     /*updates mac header */
     skb_set_mac_header(can_buff, 0);
     /*copys can header at the beginning of sk buffer */
     memcpy(skb_mac_header(can_buff), &can->can_id, sizeof(__u32) +
            sizeof(__u8));
     ce_gw_free_can_frame(can);
     return can_buff;
 }
struct sk_buff* ce_gw_eth_to_canfd (canid_t id, __u8 flags, __u8 res0, __u8 res1, struct sk_buff * eth_skb, struct net_device * dev) read
converst sk buffer including an ethernet frame to sk buffer including a canfd frame
Parameters
id identifier of canfd (see ce_gw_get_canfd_header for more information)
flags additional flags for CAN FD
res0 reserved / padding
res1 reserved / padding
eth_skb sk buffer including ethernet frame
dev device of the destination
Returns
sk buffer including canfd frame
Todo:
not tested yet
Definition at line 677 of file ce_gw_main.c.
References ce_gw_alloc_canfd_frame(), and ce_gw_free_canfd_frame().
{
     struct sk_buff *canfd_skb;
     struct canfd_frame *canfd = ce_gw_alloc_canfd_frame();
     if (canfd == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_eth_to_canfd \n");
         return NULL;
     }
     /* unsigned int ethdatalen = (skb_tail_pointer(eth_skb) - (eth_skb->data
                                + sizeof(struct ethhdr))); */
     unsigned int iplen = ip_hdrlen(eth_skb);
     /*fills canfd header */
     canfd->can_id = id;
     canfd->flags = flags;
     canfd->__res0 = res0;
     canfd->__res1 = res1;
     canfd->len = (__u8) eth_skb->data_len - sizeof(struct ethhdr);
     canfd_skb = dev_alloc_skb(sizeof(struct canfd_frame) + 64);
     if (canfd_skb == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_eth_to_canfd \n");
         return NULL;
     }
     canfd_skb->dev = dev;
     /*updates data pointer to tail */
     skb_reserve(canfd_skb, sizeof(struct canfd_frame) + 64);
     /*updates data pointer to start of network header*/
     canfd_skb->data = skb_push(canfd_skb, (const int) sizeof(__u8)*64);
     /*copys data from ethernet sk buffer into canfd sk buffer */
     memcpy(canfd_skb->data, eth_skb->data + sizeof(struct ethhdr),
            sizeof(__u8)*64);
     /*update network_header */
     skb_set_network_header(canfd_skb, 0);
     /*checks if can data length >= iplen*/
     /*updates transport header */
     if (sizeof(__u8)*64 >= iplen) {
         skb_set_transport_header(canfd_skb, (const int) iplen);
     } else {
         skb_set_transport_header(canfd_skb, sizeof(__u8)*64);
     }
     /*updates data pointer to start of mac header */
     canfd_skb->data = skb_push(canfd_skb, (const int) sizeof(struct
                                canfd_frame) - sizeof(__u8)*64);
     /*updates mac header */
     skb_set_mac_header(canfd_skb, 0);
     /*copys canfd header into sk buffer */
     memcpy(skb_mac_header(canfd_skb), &canfd->can_id, sizeof(struct
                     canfd_frame) - sizeof(__u8)*64);
     ce_gw_free_canfd_frame(canfd);
     return canfd_skb;
 }
void ce_gw_free_can_frame (struct can_frame * memory)
frees memory allocated for can_frame
Parameters
memory can frame that should be freed
Todo:
not tested yet
Definition at line 166 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_can().
 {
     kfree (memory);
 }
void ce_gw_free_canfd_frame (struct canfd_frame * memory)
frees memory allocated for can_frame
Parameters
memory canfd_frame that should be freed
Todo:
not tested yet
Definition at line 179 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_canfd().
 {
     kfree (memory);
 }
struct can_frame* ce_gw_get_header_can (canid_t can_id, __u8 can_dlc, __u8 * payload) read
builds a can header in SFF (standart frame format) or EFF (extended frame formate) with the given information
Parameters
can_id_t identifier (11/29 bits) + error flag (0=data, 1= error) + remote transmission flag (1=rtr frame) + frame format flag (0=SFF, 1=EFF)
can_dlc data length code
payload data (maximum 64 bit in an 8*8 array)
See Also
include/linux/can.h
Return values
can frame if successful
NULL if unsuccessful
Todo:
not tested yet
Definition at line 185 of file ce_gw_main.c.
References ce_gw_alloc_can_frame().
{
     struct can_frame *new_can_frame = ce_gw_alloc_can_frame();
     if (new_can_frame == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_get_header_can \n");
         return NULL;
     }
     new_can_frame->can_id = can_id;
     new_can_frame->can_dlc = can_dlc;
     *(u64 *)new_can_frame->data = *(u64 *)payload;
     return new_can_frame;
 }
struct canfd_frame* ce_gw_get_header_canfd (canid_t id, __u8 len, __u8 flags, __u8 res0, __u8 res1, __u8 * data) read
Definition at line 200 of file ce_gw_main.c.
References ce_gw_alloc_canfd_frame().
{
     struct canfd_frame *canfd = ce_gw_alloc_canfd_frame();
     if (canfd == NULL) {
         printk (KERN_ERR "ce_gw_main.c: kmalloc failed in function"
                 "ce_gw_get_header_canfd\n");
         return NULL;
     }
     canfd->can_id = id;
     canfd->len = len;
     canfd->flags = flags;
     canfd->__res0 = res0;
     canfd->__res1 = res1;
     *(u64 *)canfd->data = *(u64 *)data;
     return canfd;
 }
struct hlist_head* ce_gw_get_job_list (void) read
getter for HLIST_HEAD(ce_gw_job_list)
Returns
Pointer to ce_gw_job_list.
Definition at line 156 of file ce_gw_main.c.
Referenced by ce_gw_netlink_list().
{
     return &ce_gw_job_list;
 }
int ce_gw_remove_route (u32 id)
Definition at line 975 of file ce_gw_main.c.
References ce_gw_job::can_rcv_filter, ce_gw_unregister_can_src(), ce_gw_unregister_eth_src(), ce_gw_job::dev, ce_gw_job::dst, ce_gw_job::id, ce_gw_job::list, and ce_gw_job::src.
Referenced by ce_gw_cleanup(), and ce_gw_netlink_del().
 {
     pr_info("ce_gw: unregister CAN ETH GW routes\n");
     struct ce_gw_job *gwj = NULL;
     struct hlist_node *n, *nx;
     hlist_for_each_entry_safe(gwj, n, nx, &ce_gw_job_list, list) {
         if (gwj->id != id && id)
             continue;
         pr_debug("Removing routing src device: %s, id %x, mask %x\n",
                  gwj->src.dev->name, gwj->can_rcv_filter.can_id,
                  gwj->can_rcv_filter.can_mask);
         hlist_del(&gwj->list);
         /* TODO: Unregister destination device (only for cegw eth) */
         if (gwj->src.dev->type == ARPHRD_CAN)
             ce_gw_unregister_can_src(gwj);
         else
             ce_gw_unregister_eth_src(gwj);
         dev_put(gwj->src.dev);
         dev_put(gwj->dst.dev);
         kmem_cache_free(ce_gw_job_cache, gwj);
     }
     return 0; /* TODO: error, when no suitable entry was found */
 }
Variable Documentation
union { ... }
Filter incoming packet
struct can_filter can_rcv_filter
Definition at line 102 of file ce_gw_main.h.
Referenced by ce_gw_create_route(), ce_gw_register_can_src(), ce_gw_remove_route(), and ce_gw_unregister_can_src().
struct can_filter can_rcv_filter
Definition at line 102 of file ce_gw_main.h.
struct net_device* dev
Definition at line 96 of file ce_gw_main.h.
struct net_device* dev
Definition at line 96 of file ce_gw_main.h.
Referenced by ce_gw_can_rcv(), ce_gw_create_route(), ce_gw_eth_rcv(), ce_gw_netlink_list(), ce_gw_register_can_src(), ce_gw_remove_route(), ce_gw_unregister_can_src(), and list_jobs().
struct net_device* dev
Definition at line 99 of file ce_gw_main.h.
u32 dropped_frames
counter for dropped_frames
Definition at line 93 of file ce_gw_main.h.
Referenced by ce_gw_can_rcv(), ce_gw_create_route(), ce_gw_eth_rcv(), ce_gw_netlink_list(), and test_hash_list().
union { ... } dst
CAN / ETH frame data destination
Referenced by ce_gw_can_rcv(), ce_gw_create_route(), ce_gw_eth_rcv(), ce_gw_netlink_list(), ce_gw_remove_route(), and list_jobs().
u32 flags
Flags with settings of the Gateway
Definition at line 91 of file ce_gw_main.h.
Referenced by ce_gw_create_route(), and ce_gw_netlink_list().
u32 handled_frames
counter for handles frames
Definition at line 92 of file ce_gw_main.h.
Referenced by ce_gw_can_rcv(), ce_gw_create_route(), ce_gw_eth_rcv(), and ce_gw_netlink_list().
u32 id
Unique Identifier of Gateway
Definition at line 89 of file ce_gw_main.h.
Referenced by ce_gw_create_route(), ce_gw_eth_rcv(), ce_gw_netlink_list(), ce_gw_remove_route(), and list_jobs().
struct hlist_node list
List entry for ce_gw_job_list main list
Definition at line 86 of file ce_gw_main.h.
Referenced by ce_gw_create_route(), ce_gw_remove_route(), and test_hash_list().
struct hlist_node list_dev
List entry from the ETH device
Definition at line 88 of file ce_gw_main.h.
struct rcu_head rcu
Lock monitor
Definition at line 87 of file ce_gw_main.h.
union { ... } src
CAN / ETH frame data source
Referenced by ce_gw_can_rcv(), ce_gw_create_route(), ce_gw_netlink_list(), ce_gw_register_can_src(), ce_gw_remove_route(), ce_gw_unregister_can_src(), and list_jobs().
enum ce_gw_type type
Translation type of the Gateway
Definition at line 90 of file ce_gw_main.h.
Referenced by ce_gw_can_rcv(), ce_gw_create_route(), ce_gw_eth_rcv(), and ce_gw_netlink_list().