can_eth_gw Gateway Module: Device
Device
int ce_gw_dev_open (struct net_device *dev)
called by the OS on device up
int ce_gw_dev_stop (struct net_device *dev)
called by the OS on device down
static int ce_gw_dev_start_xmit (struct sk_buff *skb, struct net_device *dev)
called by the OS if a package is sent to the device
int ce_gw_dev_init (struct net_device *dev)
called by the OS on device registered
int ce_gw_is_allocated_dev (struct net_device *eth_dev)
check if the param eth_dev is allocated by this module
int ce_gw_is_registered_dev (struct net_device *eth_dev)
check if the param eth_dev is registered by this module
void ce_gw_dev_job_src_add (struct ce_gw_job *job)
Adds an pointer to the net_device internal list where it is the src.
void ce_gw_dev_job_dst_add (struct ce_gw_job *job)
Adds an pointer to the net_device internal list where it is the dst.
int ce_gw_dev_job_add (struct net_device *eth_dev, struct ce_gw_job *job)
Adds an pointer to the net_device internal list where it is part of.
void ce_gw_dev_job_remove (struct ce_gw_job *job)
Removes the pointer to param job from the list in ethernet net_device.
struct net_device * ce_gw_dev_alloc (void)
Allocates a Ethernet Device for the Gateway.
void ce_gw_dev_free (struct net_device *eth_dev)
Free virtual ethernet device and remove from internal lists.
void ce_gw_dev_setup (struct net_device *dev, enum ce_gw_type type, __u32 flags)
Sets the default attributes for the Gateway Ethernet device.
struct net_device * ce_gw_dev_create (enum ce_gw_type type, __u32 flags)
Allocate the device and set standart Attributes with ce_gw_dev_setup()
int ce_gw_dev_register (struct net_device *eth_dev)
Register a virtual ethernet device on the OS.
void ce_gw_dev_unregister (struct net_device *eth_dev)
Unregister virtual ethernet device and remove from internal lists.
int ce_gw_dev_init_module (void)
Initialise all objects, wich are needed by the other functions.
void ce_gw_dev_cleanup (void)
Deleting all objects created by ce_gw_dev_init_module() and all devices.
Detailed Description
Function Documentation
struct net_device * ce_gw_dev_alloc (void) read
Allocates a Ethernet Device for the Gateway.
Allocates a Ethernet Device with struct ce_gw_job_info as private data. ce_gw_dev_setup() should be called after this function. free_netdev(dev) musst be called for freeing the memory.
Return values
NULL If an error has occured.
Returns
A pointer to the allocated device.
Definition at line 316 of file ce_gw_dev.c.
References ce_gw_dev_list::dev, ce_gw_job_info::job_dst, ce_gw_job_info::job_src, and ce_gw_dev_list::list_alloc.
Referenced by ce_gw_dev_create().
{
     pr_debug("ce_gw_dev: Alloc Device\n");
     struct net_device *dev;
     dev = alloc_netdev(sizeof(struct ce_gw_job_info),
                        "cegw%d", ether_setup);
     if (dev == NULL) {
         pr_err("ce_gw_dev: Error allocation etherdev.");
         goto ce_gw_dev_create_error;
     }
     /* initialize private field */
     struct ce_gw_job_info *priv = netdev_priv(dev);
     memset(priv, 0, sizeof(struct ce_gw_job_info));
     priv->job_src.first = NULL;
     priv->job_dst.first = NULL;
     /* create list entry and add */
     struct ce_gw_dev_list *dl;
     dl = kmem_cache_alloc(ce_gw_dev_cache, GFP_KERNEL);
     if (dl == NULL) {
         pr_err("ce_gw_dev: cache alloc failed");
         goto ce_gw_dev_create_error_cache;
     }
     dl->dev = dev;
     hlist_add_head_rcu(&dl->list_alloc, &ce_gw_dev_allocated);
     return dev;
 ce_gw_dev_create_error_cache:
     kmem_cache_free(ce_gw_dev_cache, dl);
 ce_gw_dev_create_error:
     free_netdev(dev);
     return NULL;
 }
void ce_gw_dev_cleanup (void)
Deleting all objects created by ce_gw_dev_init_module() and all devices.
Postcondition
after this function is called the other functions could not be used any more
Definition at line 612 of file ce_gw_dev.c.
References ce_gw_dev_free(), ce_gw_dev_unregister(), and ce_gw_dev_list::dev.
Referenced by ce_gw_cleanup().
{
     struct ce_gw_dev_list *dl = NULL;
     struct hlist_node *node;
     /* iterate over list and unregister */
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(dl, node, &ce_gw_dev_registered, list_reg) {
 #   else
     struct hlist_node *pos;
     hlist_for_each_entry_safe(dl, pos, node, &ce_gw_dev_registered,
                               list_reg) {
 #   endif
         ce_gw_dev_unregister(dl->dev);
     }
     dl = NULL;
     node = NULL;
     /* iterate over list and free */
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(dl, node, &ce_gw_dev_allocated, list_alloc) {
 #   else
     pos = NULL;
     hlist_for_each_entry_safe(dl, pos, node, &ce_gw_dev_allocated,
                               list_alloc) {
 #   endif
         ce_gw_dev_free(dl->dev);
     }
     kmem_cache_destroy(ce_gw_dev_cache);
 }
struct net_device * ce_gw_dev_create (enum ce_gw_type type, __u32 flags) read
Allocate the device and set standart Attributes with ce_gw_dev_setup()
Parameters
type Type of the Gateway wich will be linked to the device. A sensible MTU will be set. Use CE_GW_TYPE_NONE for default ethernet MTU.
flags If CE_GW_F_CAN_FD Flag is set the MTU will be set to the CAN-FD size else to the normal CAN size.
Returns
A pointer to the allocated and configured device.
Definition at line 450 of file ce_gw_dev.c.
References ce_gw_dev_alloc(), and ce_gw_dev_setup().
Referenced by ce_gw_netlink_add().
{
     struct net_device *dev;
     dev = ce_gw_dev_alloc();
     ce_gw_dev_setup(dev, type, flags);
     return dev;
 }
void ce_gw_dev_free (struct net_device * eth_dev)
Free virtual ethernet device and remove from internal lists.
Precondition
ce_gw_dev_unregister() was already called
Parameters
eth_dev the virtual ethernet device allocated by ce_gw_dev_alloc()
Definition at line 362 of file ce_gw_dev.c.
References ce_gw_dev_list::dev, and ce_gw_dev_list::list_alloc.
Referenced by ce_gw_dev_cleanup(), ce_gw_netlink_add(), and ce_gw_netlink_del().
{
     pr_debug("ce_gw_dev: Free Device %s\n", eth_dev->name);
     struct ce_gw_dev_list *dl = NULL;
     struct hlist_node *node;
     /* search for the List Element of eth_dev */
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(dl, node, &ce_gw_dev_allocated, list_alloc) {
 #   else
     struct hlist_node *pos;
     hlist_for_each_entry_safe(dl, pos, node, &ce_gw_dev_allocated,
                               list_alloc) {
 #   endif
         if (dl->dev == eth_dev)
             break;
     }
     if (dl == NULL || dl->dev != eth_dev) {
         pr_err("ce_gw_dev: Device not found in list\n");
     } else {
         hlist_del_rcu(&dl->list_alloc);
     }
     free_netdev(eth_dev);
     kmem_cache_free(ce_gw_dev_cache, dl);
 }
static int ce_gw_dev_init (struct net_device * dev)
called by the OS on device registered
Parameters
dev correspondening eth device
Return values
0 on success
<0 on failure
Definition at line 151 of file ce_gw_dev.c.
{
     printk ("ce_gw_dev: device init called\n");
     return 0;
 }
int ce_gw_dev_init_module (void)
Initialise all objects, wich are needed by the other functions.
Postcondition
the other functions of the file could only be used after this function was called
Return values
0 on success
<0 on failure
Definition at line 594 of file ce_gw_dev.c.
Referenced by ce_gw_init_module().
{
     ce_gw_dev_cache = kmem_cache_create("can_eth_gw_dev",
                                         sizeof(struct ce_gw_dev_list),
                                         0, 0, NULL);
     if (!ce_gw_dev_cache)
         return -ENOMEM;
     return 0;
 }
void ce_gw_dev_job_add (struct net_device * eth_dev, struct ce_gw_job * job)
Adds an pointer to the net_device internal list where it is part of.
The Function will add a Pointer to the list in the net_device private field back to the param job. There must be a pointer in union src or union dst in the param job to the struct net_device *eth_dev.
Precondition
union src.dev or union dst.dev in param job must already point to the param eth_dev.
Parameters
eth_dev The ethernet struct net_device witch is pointed from union src or union dst in param job.
job The struct ce_gw_job where union src or union dst points to the param eth_dev. A Pointer to this param will be added.
Return values
0 success
<0 failure
Definition at line 277 of file ce_gw_dev.c.
References ce_gw_dev_job_dst_add(), ce_gw_dev_job_src_add(), ce_gw_job::dev, ce_gw_job::dst, and ce_gw_job::src.
{
     if (job->src.dev == eth_dev) {
         ce_gw_dev_job_src_add(job);
     } else if (job->dst.dev == eth_dev) {
         ce_gw_dev_job_dst_add(job);
     } else {
         pr_err("ce_gw_dev_job_add: Invalid Arguments");
         return -1;
     }
     return 0;
 }
void ce_gw_dev_job_dst_add (struct ce_gw_job * job)
Adds an pointer to the net_device internal list where it is the dst.
The Function will add a Pointer to the list in the net_device private field back to the param job. The pointer in union dst.dev in the param job be set to the param eth_dev.
Precondition
union dst.dev in param job must already point to the ethernet device.
Parameters
job The struct ce_gw_job where union dst will points to the param eth_dev. A Pointer to this param will be added.
The Function will add a Pointer to the list in the net_device private field back to the param job. The pointer in union dst.dev in the param job be set to the param eth_dev.
Precondition
union dst.dev in param job must already point to the ethernet device.
Parameters
eth_dev The ethernet struct net_device witch will be pointed from union dst in param job.
job The struct ce_gw_job where union dst will points to the param eth_dev. A Pointer to this param will be added.
Definition at line 254 of file ce_gw_dev.c.
References ce_gw_job::dev, ce_gw_job::dst, ce_gw_job_info::job_dst, and ce_gw_job::list_dev.
Referenced by ce_gw_dev_job_add().
{
     struct ce_gw_job_info *priv = netdev_priv(job->dst.dev);
     hlist_add_head_rcu(&job->list_dev, &priv->job_dst);
 }
void ce_gw_dev_job_remove (struct ce_gw_job * job)
Removes the pointer to param job from the list in ethernet net_device.
The private field of the ethernet struct net_device contains a a pointer to the param job. The Function will remove this Pointer from the list.
Parameters
job The struct ce_gw_job where union src or union dst points to the param eth_dev. A Pointer to this param will be removed.
Warning
You must remove the pointer from union src and accordingly union dst in param job to the ethernet struct net_device yourself. Until you do this our pointer architecture is inconsistent.
Definition at line 302 of file ce_gw_dev.c.
References ce_gw_job::list_dev.
Referenced by ce_gw_unregister_eth_src().
{
     hlist_del_rcu(&job->list_dev);
 }
void ce_gw_dev_job_src_add (struct ce_gw_job * job)
Adds an pointer to the net_device internal list where it is the src.
The Function will add a Pointer to the list in the net_device private field back to the param job. The pointer in union src.dev in the param job be set to the param eth_dev.
Precondition
union src.dev in param job must already point to the ethernet device.
Parameters
job The struct ce_gw_job where union src will points to the param eth_dev. A Pointer to this param will be added.
The Function will add a Pointer to the list in the net_device private field back to the param job. The pointer in union src.dev in the param job be set to the param eth_dev.
Precondition
union src.dev in param job must already point to the ethernet device.
Parameters
eth_dev The ethernet struct net_device witch will be pointed from union src in param job.
job The struct ce_gw_job where union src will points to the param eth_dev. A Pointer to this param will be added.
Definition at line 238 of file ce_gw_dev.c.
References ce_gw_job::dev, ce_gw_job_info::job_src, ce_gw_job::list_dev, and ce_gw_job::src.
Referenced by ce_gw_dev_job_add(), and ce_gw_register_eth_src().
{
     struct ce_gw_job_info *priv = netdev_priv(job->src.dev);
     hlist_add_head_rcu(&job->list_dev, &priv->job_src);
 }
int ce_gw_dev_open (struct net_device * dev)
called by the OS on device up
Parameters
dev correspondening eth device
Return values
0 on success
<0 on failure
Definition at line 72 of file ce_gw_dev.c.
 {
     printk("ce_gw: ce_gw_open called\n");
     if (!netif_device_present(dev)) {
         pr_err("ce_gw_dev_open: Device not registered");
         return -1;
     }
     netif_start_queue(dev);
     return 0;
 }
int ce_gw_dev_register (struct net_device * eth_dev)
Register a virtual ethernet device on the OS.
Parameters
eth_dev the virtual ethernet device
Precondition
param eth_dev was previously allocated by ce_gw_dev_alloc()
Return values
0 on success
<0 on failure
Definition at line 468 of file ce_gw_dev.c.
References ce_gw_dev_list::dev, and ce_gw_dev_list::list_reg.
Referenced by ce_gw_netlink_add().
{
     pr_debug("ce_gw_dev: Register Device\n");
     int err = 0;
     err = register_netdev(eth_dev);
     struct ce_gw_dev_list *dl = NULL;
     struct hlist_node *node;
     /* search for the List Element of eth_dev */
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(dl, node, &ce_gw_dev_allocated, list_alloc) {
 #   else
     struct hlist_node *pos;
     hlist_for_each_entry_safe(dl, pos, node, &ce_gw_dev_allocated,
                               list_alloc) {
 #   endif
         if (dl->dev == eth_dev)
             break;
     }
     if (dl == NULL || dl->dev != eth_dev) {
         pr_err("ce_gw_dev: Device not found in list\n");
         goto ce_gw_dev_register_error;
     }
     hlist_add_head_rcu(&dl->list_reg, &ce_gw_dev_registered);
     if (&dl->list_reg == NULL) {
         pr_err("ce_gw_dev: Device not add to list correct\n");
     }
     return err;
 ce_gw_dev_register_error:
     unregister_netdev(eth_dev);
     return err;
 }
void ce_gw_dev_setup (struct net_device * dev, enum ce_gw_type type, __u32 flags)
Sets the default attributes for the Gateway Ethernet device.
Parameters
type Type of the Gateway wich will be linked to the device. A sensible MTU will be set. Use CE_GW_TYPE_NONE for default ethernet MTU.
flags If CE_GW_F_CAN_FD Flag is set the MTU will be set to the CAN-FD size else to the normal CAN size.
dev the ethernet device which should be set up
Sets the default attributes for the Gateway Ethernet device. Also links the net_device operations to the net_dev structure. ce_gw_dev_register() should be called afterwards for registering, ce_gw_dev_unregister() for unregistering at the end.
Parameters
type Type of the Gateway wich will be linked to the device. A sensible MTU will be set. Use CE_GW_TYPE_NONE for default ethernet MTU.
flags If CE_GW_F_CAN_FD Flag is set the MTU will be set to the CAN-FD size else to the normal CAN size.
Sets the default attributes for the Gateway Ethernet device. Also links the net_device operations to the net_dev structure. ce_gw_dev_register() should be called afterwards for registering, ce_gw_dev_unregister() for unregistering at the end.
Definition at line 406 of file ce_gw_dev.c.
References CE_GW_F_CAN_FD, ce_gw_ops, CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_NONE, CE_GW_TYPE_TCP, and CE_GW_TYPE_UDP.
Referenced by ce_gw_dev_create().
{
     dev->netdev_ops = &ce_gw_ops;
     /* Set sensible MTU */
     switch (type) {
     case CE_GW_TYPE_NONE:
         /* Do Nothing (default Ethernet MTU will be set) */
         break;
     case CE_GW_TYPE_ETH:
         if ((flags & CE_GW_F_CAN_FD) == CE_GW_F_CAN_FD) {
             dev->mtu = CANFD_MAX_DLEN;
         } else {
             dev->mtu = CAN_MAX_DLEN;
         }
         break;
     case CE_GW_TYPE_NET:
         if ((flags & CE_GW_F_CAN_FD) == CE_GW_F_CAN_FD) {
             dev->mtu = sizeof(struct canfd_frame);
         } else {
             dev->mtu = sizeof(struct can_frame);
         }
         break;
     case CE_GW_TYPE_TCP:
         /* TODO nothing yet */
         break;
     case CE_GW_TYPE_UDP:
         /* TODO nothing yet */
         break;
     default:
         pr_err("ce_gw_dev: Type not defined.");
     }
 }
static int ce_gw_dev_start_xmit (struct sk_buff * skb, struct net_device * dev) static
called by the OS if a package is sent to the device
Parameters
dev correspondening eth device
skb sk buffer from OS
Return values
0 on success
<0 on failure
Definition at line 110 of file ce_gw_dev.c.
References ce_gw_eth_rcv(), and ce_gw_job_info::job_src.
 {
     printk ("ce_gw_dev: dummy xmit function called....\n");
     /* TODO: Get right gw_job and push it to eth_skb (instead of NULL) */
     struct ce_gw_job_info *priv = netdev_priv(dev);
     struct ce_gw_job *job = NULL;
     struct hlist_node *node;
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(job, node, &priv->job_src, list_dev) {
 #   else
     struct hlist_node *pos;
     hlist_for_each_entry_safe(job, pos, node, &priv->job_src,
                               list_dev) {
 #   endif
         ce_gw_eth_rcv(skb, job);
     }
     dev_kfree_skb(skb);
     /*here is my test for ce_gw_eth_to_canfd*/
     /*  struct sk_buff *can_skb;*/
     /*  __u32 id = 0xF65C034B;*/
     /*  __u8 flags = 0x04;*/
     /*  __u8 res0 = 0xF3;*/
     /*  __u8 res1 = 0x00;*/
     /*  can_skb = ce_gw_eth_to_canfd(id, flags, res0, res1, skb, dev);*/
     return 0;
 }
int ce_gw_dev_stop (struct net_device * dev)
called by the OS on device down
Parameters
dev correspondening eth device
Return values
0 on success
<0 on failure
Definition at line 93 of file ce_gw_dev.c.
 {
     printk ("ce_gw_dev: ce_gw_release called\n");
     netif_stop_queue(dev);
     return 0;
 }
void ce_gw_dev_unregister (struct net_device * eth_dev)
Unregister virtual ethernet device and remove from internal lists.
Parameters
eth_dev the virtual ethernet device
Precondition
param eth_dev was previously registered by ce_gw_dev_register()
Definition at line 513 of file ce_gw_dev.c.
References ce_gw_remove_route(), ce_gw_dev_list::dev, ce_gw_job::id, ce_gw_job_info::job_dst, ce_gw_job_info::job_src, and ce_gw_dev_list::list_reg.
Referenced by ce_gw_dev_cleanup(), and ce_gw_netlink_del().
{
     pr_debug("ce_gw_dev: Unregister Device %s\n", eth_dev->name);
     int err = 0;
     struct ce_gw_job_info *priv = netdev_priv(eth_dev);
     pr_debug("ce_gw_dev: Deleting all Routes of %s\n", eth_dev->name);
     /* Delete all routes witch are linked to the soon unregistered device
      * where the device is the source */
     struct ce_gw_job *job = NULL;
     struct hlist_node *node;
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(job, node, &priv->job_src, list_dev) {
 #   else
     struct hlist_node *pos;
     hlist_for_each_entry_safe(job, pos, node, &priv->job_src, list_dev) {
 #   endif
         err = ce_gw_remove_route(job->id);
         if (err != 0) {
             pr_err("ce_gw_dev: route with id %u "
                    "deleting failed: %d", job->id, err);
         }
     }
     /* Delete all routes witch are linked to the soon unregistered device
      * where the device is the dest */
     job = NULL;
     node = NULL;
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(job, node, &priv->job_dst, list_dev) {
 #   else
     pos = NULL;
     hlist_for_each_entry_safe(job, pos, node, &priv->job_dst, list_dev) {
 #   endif
         err = ce_gw_remove_route(job->id);
         {
             pr_err("ce_gw_dev: route with id %u "
                    "deleting failed: %d", job->id, err);
         }
     }
     /* unregister */
     pr_debug("ce_gw_dev: Call unregister_netdev() of %s\n", eth_dev->name);
     unregister_netdev(eth_dev);
     struct ce_gw_dev_list *dl = NULL;
     node = NULL;
     /* search for the List Element of eth_dev */
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(dl, node, &ce_gw_dev_registered, list_reg) {
 #   else
     pos = NULL;
     hlist_for_each_entry_safe(dl, pos, node, &ce_gw_dev_registered,
                               list_reg) {
 #   endif
         if (dl->dev == eth_dev)
             break;
     }
     if (dl == NULL || &dl->list_reg == NULL) {
         pr_err("ce_gw_dev: Device not correct in internal list\n");
     } else {
         hlist_del_rcu(&dl->list_reg);
     }
 }
int ce_gw_is_allocated_dev (struct net_device * eth_dev)
check if the param eth_dev is allocated by this module
check if the param eth_dev is registered by this module
Parameters
eth_dev the device wich should be checked
Return values
0 param eth_dev was allocated by this module
-ENODEV param eth_dev was NOT allocated by this module
others error occured
See Also
ce_gw_is_registered_dev() should you normally use
Parameters
eth_dev the device wich should be checked
Return values
0 param eth_dev was registered by this module
-ENODEV param eth_dev was NOT registered by this module
others error occured
Definition at line 177 of file ce_gw_dev.c.
References ce_gw_dev_list::dev.
{
     struct ce_gw_dev_list *dl = NULL;
     struct hlist_node *node;
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(dl, node, &ce_gw_dev_allocated, list_alloc) {
 #   else
     struct hlist_node *pos;
     hlist_for_each_entry_safe(dl, pos, node, &ce_gw_dev_allocated,
                               list_alloc) {
 #   endif
         if (dl->dev == eth_dev)
             return 0;
     }
     return -ENODEV;
 }
int ce_gw_is_registered_dev (struct net_device * eth_dev)
check if the param eth_dev is registered by this module
Parameters
eth_dev the device wich should be checked
Return values
0 param eth_dev was registered by this module
-ENODEV param eth_dev was NOT registered by this module
others error occured
Definition at line 206 of file ce_gw_dev.c.
References ce_gw_dev_list::dev.
Referenced by ce_gw_create_route().
{
     struct ce_gw_dev_list *dl = NULL;
     struct hlist_node *node;
 #   if LINUX_VERSION_CODE >= KERNEL_VERSION(3,9,0)
     hlist_for_each_entry_safe(dl, node, &ce_gw_dev_registered, list_reg) {
 #   else
     struct hlist_node *pos;
     hlist_for_each_entry_safe(dl, pos, node, &ce_gw_dev_registered,
                               list_reg) {
 #   endif
         if (dl->dev == eth_dev)
             return 0;
     }
     pr_debug("ce_gw_is_registered_dev: Device not registered\n");
     return -ENODEV;
 }