can_eth_gw Gateway Module: Create & Deleting
Create & Deleting
static int __init ce_gw_init_module (void)
Will be automatic called at module init.
static void __exit ce_gw_cleanup (void)
Will be automatically called on module remove.
struct can_frame * ce_gw_alloc_can_frame (void)
allocates memory for the can frame
void ce_gw_free_can_frame (struct can_frame *memory)
frees memory allocated for can_frame
struct canfd_frame * ce_gw_alloc_canfd_frame (void)
allocates memory for a canfd frame
void ce_gw_free_canfd_frame (struct canfd_frame *memory)
frees memory allocated for can_frame
Detailed Description
Function Documentation
struct can_frame * ce_gw_alloc_can_frame (void) read
allocates memory for the can frame
Returns
pointer to the memory allocated
Todo:
not tested yet
Definition at line 161 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_can(), and ce_gw_get_header_can().
{
     struct can_frame *memory;
     memory = kmalloc(sizeof(struct can_frame),GFP_KERNEL);
     return memory;
 }
struct canfd_frame * ce_gw_alloc_canfd_frame (void) read
allocates memory for a canfd frame
Returns
pointer to the memory allocated
Todo:
not tested yet
Definition at line 173 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_canfd(), and ce_gw_get_header_canfd().
{
     struct canfd_frame *memory;
     memory = kmalloc(sizeof(struct canfd_frame), GFP_KERNEL);
     return memory;
 }
static void __exit ce_gw_cleanup (void) static
Will be automatically called on module remove.
Definition at line 1048 of file ce_gw_main.c.
References ce_gw_dev_cleanup(), ce_gw_netlink_exit(), and ce_gw_remove_route().
 {
     printk(KERN_INFO "ce_gw: Cleaning up the module\n");
     pr_debug("ce_gw: Unregister netlink server.\n");
     ce_gw_netlink_exit();
     /* Unregister all routes */
     pr_info("ce_gw: unregister all CAN ETH GW routes\n");
     ce_gw_remove_route(0);
     pr_debug("ce_gw: Unregister virtual net devices.\n");
     ce_gw_dev_cleanup();
     /* Mem cleanup */
     kmem_cache_destroy(ce_gw_job_cache);
 }
void ce_gw_free_can_frame (struct can_frame * memory)
frees memory allocated for can_frame
Parameters
memory can frame that should be freed
Todo:
not tested yet
Definition at line 167 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_can().
 {
     kfree (memory);
 }
void ce_gw_free_canfd_frame (struct canfd_frame * memory)
frees memory allocated for can_frame
Parameters
memory canfd_frame that should be freed
Todo:
not tested yet
Definition at line 180 of file ce_gw_main.c.
Referenced by ce_gw_eth_to_canfd().
 {
     kfree (memory);
 }
static int __init ce_gw_init_module (void) static
Will be automatic called at module init.
Return values
0 on success
>0 on failure
Tests: remove when done!
END TEST
Definition at line 1016 of file ce_gw_main.c.
References ce_gw_dev_init_module(), ce_gw_netlink_init(), and list_jobs().
 {
     int err = 0;
     printk(KERN_INFO "ce_gw: Module started.\n");
     ce_gw_job_cache = kmem_cache_create("can_eth_gw",
                                         sizeof(struct ce_gw_job), 0, 0, NULL);
     if (!ce_gw_job_cache)
         return ENOMEM;
     list_jobs();
     err = ce_gw_netlink_init();
     err += ce_gw_dev_init_module();
     if (err != 0)
         return 1;
     else
         return 0;
 }