can_eth_gw Gateway Module: Processing
Processing
void ce_gw_can_rcv (struct sk_buff *can_skb, void *data)
The gateway function for incoming CAN frames Receive CAN frame –> process –> send to ETH dev (skbuffer, struct receiver->data)
void ce_gw_eth_rcv (struct sk_buff *eth_skb, void *data)
The gateway function for incoming ETH frames Receive skb from ETH dev –> process –> send to CAN bus.
Detailed Description
Function Documentation
void ce_gw_can_rcv (struct sk_buff * can_skb, void * data)
The gateway function for incoming CAN frames Receive CAN frame –> process –> send to ETH dev (skbuffer, struct receiver->data)
Parameters
can_skb CAN sk buffer which should be translated to an ETH packet
data gwjob which is responsible for triggering this function
Todo:
check also for canfd flag not only Type and call function. You must also check then if the message then is really a canfd-frame or not.
call other translation functions. check for canfd-frame or only use canfd-frame casts.
Definition at line 759 of file ce_gw_main.c.
References ce_gw_can2net_alloc(), CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_TCP, CE_GW_TYPE_UDP, ce_gw_job::dev, ce_gw_job::dropped_frames, ce_gw_job::dst, ce_gw_job::handled_frames, ce_gw_job::src, and ce_gw_job::type.
Referenced by ce_gw_register_can_src(), and ce_gw_unregister_can_src().
 {
     int err = 0;
     struct can_frame *cf;
     /* CAN frame (id, dlc, data)*/
     cf = (struct can_frame *)can_skb->data;
     pr_debug("Incoming msg from can dev: can_id %x, len %i, can_msg %x\n",
              cf->can_id, cf->can_dlc, cf->data[0]);
     struct ce_gw_job *cgj = (struct ce_gw_job *)data;
     struct sk_buff *eth_skb = NULL;
     long long dmac = 0xffffffffffff;
     long long smac = 0x000000000000;
     switch (cgj->type) {
     case CE_GW_TYPE_ETH:
         pr_info("Translation ETH not implemented yet.");
         break;
     case CE_GW_TYPE_NET:
         eth_skb = ce_gw_can2net_alloc(can_skb,
                                       cgj->dst.dev,
                                       cgj->src.dev,
                                       (unsigned char *) &dmac,
                                       (unsigned char *) &smac);
         break;
     case CE_GW_TYPE_TCP:
         pr_info("Translation IP TCP not implemented yet.");
         break;
     case CE_GW_TYPE_UDP:
         pr_info("Translation IP UDP not implemented yet.");
         break;
     default:
         pr_err("ce_gw: Translation type of ce_gw_job not "
                "implemented. BUG: Some module inserted an invalid "
                "type. Use enum ce_gw_type instead.");
         goto drop_frame;
         break;
     }
     err = netif_rx_ni(eth_skb);
     if (err != 0) {
         pr_err("ce_gw: send to kernel failed");
         cgj->dropped_frames++;
         goto exit_error;
     }
     cgj->handled_frames++;
     /* TODO If you use kfree_skb(can_skb) the system hang up completely
      * without printing stack trace. But a few packets normally passed
      * before sytem hang up. But <linux/can/dev.h> uses kfree_skb(). There
      * is no refdata count left. The reason why hang up is completely
      * unknown. */
 exit_error:
     pr_info("ce_gw: WARNING can skb will not be freed");
     /*kfree_skb(can_skb);*/
     return;
 drop_frame:
     cgj->dropped_frames++;
     dev_kfree_skb(eth_skb);
     return;
 }
static void ce_gw_eth_rcv (struct sk_buff * eth_skb, void * data)
The gateway function for incoming ETH frames Receive skb from ETH dev –> process –> send to CAN bus.
Parameters
eth_skb ETH sk buffer with CAN frame as payload. Exact location of CAN frame depends on translation type (see enum ce_gw_type)
data gwjob which is responsible for triggering this function
Todo:
check for canfd-frame or only use canfd-frame casts.
Definition at line 829 of file ce_gw_main.c.
References ce_gw_net2can_alloc(), CE_GW_TYPE_ETH, CE_GW_TYPE_NET, CE_GW_TYPE_TCP, CE_GW_TYPE_UDP, ce_gw_job::dev, ce_gw_job::dropped_frames, ce_gw_job::dst, ce_gw_job::handled_frames, ce_gw_job::id, and ce_gw_job::type.
Referenced by ce_gw_dev_start_xmit().
 {
     struct ce_gw_job *gwj = (struct ce_gw_job *)data;
     /* Create Can skb and convert incoming Eth sk buffer depending on
      * type (ce_gw_type in gwj)
      */
     struct sk_buff *can_skb = NULL;
     switch (gwj->type) {
     case CE_GW_TYPE_ETH:
         pr_info("Translation ETH not implemented yet.");
         break;
     case CE_GW_TYPE_NET:
         can_skb = ce_gw_net2can_alloc(eth_skb, gwj->dst.dev);
         break;
     case CE_GW_TYPE_TCP:
         pr_info("Translation IP TCP not implemented yet.");
         break;
     case CE_GW_TYPE_UDP:
         pr_info("Translation IP UDP not implemented yet.");
         break;
     default:
         printk(KERN_ERR "ce_gw: Translation type of ce_gw_job not "
                "implemented. BUG: Some module inserted an invalid "
                "type. Use enum ce_gw_type instead.");
         goto drop_frame;
         break;
     }
     /* Memory allocation or translation ETH -> CAN failed */
     if (!can_skb)
         goto drop_frame;
     struct can_frame *cf;
     cf = (struct can_frame *)can_skb->data;
     pr_debug("Incoming msg from eth dev (gwj %i): "
              "can_id %x, len %i, can_msg(1) %x\n",
              gwj->id, cf->can_id, cf->can_dlc, cf->data[0]);
     /* send to CAN netdevice (with echo flag for loopback devices) */
     if (can_send(can_skb, 0x01))
         goto drop_frame;
     else
         gwj->handled_frames++;
     return; /* Receive + process + send to CAN successful */
 drop_frame:
     gwj->dropped_frames++;
     dev_kfree_skb(can_skb);
     return;
 }