can-eth-gw-utils Gateway Utilities: netlink.h File Reference
netlink.h File Reference
Control Area Network - Ethernet - Gateway - Netlink Header (Utility)
#include <stdint.h>
Macros
#define F_CAN_FD 0x00000001
#define TYPE_MAX (__TYPE_MAX - 1)
Enumerations
enum gw_type {
TYPE_NONE, TYPE_ETH, TYPE_NET, TYPE_TCP,
TYPE_UDP, __TYPE_MAX
}
Functions
int ce_gw_add (char *src_name, char *dst_name, uint8_t type, uint32_t flags)
add a virtual ethernet device or a route
int ce_gw_del (uint32_t id, char *dev_name)
Deletes a device or a route in Kernel Module.
int ce_gw_list (uint32_t id)
Print informations of actual active routes to stdout.
int ce_gw_echo (char *message)
send a message and return the received message from Kernel.
int nl_sk_fam_init (void)
creakte socket and family and connect
void nl_sk_fam_exit (void)
freeing the alloccated memory. The Function free the memory allocated by nl_sk_fam_init().
Detailed Description
Control Area Network - Ethernet - Gateway - Netlink Header (Utility)
Author
Fabian Raab (fabia.nosp@m.n.ra.nosp@m.ab@tu.nosp@m.m.de)
Date
May, 2013
Copyright
GNU Public License v3 or higher
Definition in file netlink.h.
Macro Definition Documentation
#define F_CAN_FD 0x00000001
Definition at line 34 of file netlink.h.
Referenced by main().
#define TYPE_MAX (__TYPE_MAX - 1)
Definition at line 46 of file netlink.h.
Referenced by nl_cb_list_entry().
Enumeration Type Documentation
enum gw_type
Enumerator
TYPE_NONE
No Type. Schould normally not used.
TYPE_ETH
Convert CAN Header to Ethernet Header
TYPE_NET
Copy complete CAN Frame into Ethernet payload. e.g use CAN als Network Layer (Layer 3) Protocol.
TYPE_TCP
Convert CAN Header into an IP/TCP Package
TYPE_UDP
Convert CAN Header into an IP/UDP Package
__TYPE_MAX
Maximum Type Number + 1
Definition at line 37 of file netlink.h.
              {
     TYPE_NONE,
     TYPE_ETH,
     TYPE_NET,
     TYPE_TCP,
     TYPE_UDP,
     __TYPE_MAX,
 };
Function Documentation
int ce_gw_add (char * src_name, char * dst_name, uint8_t type, uint32_t flags)
add a virtual ethernet device or a route
Parameters
src_name The textual name of the device wich will be the src. Must be NULL if you want do add a device.
src_name The textual name of the device wich will be the dst. Must be NULL if you want do add a device.
type The Type of the route. For adding dev some settings according to the type will be set.
type The Flags of the route. For adding dev some settings according to the type will be set. See netlink.h for the falgs.
See Also
related callbacks: nl_cb_general_errno()
Definition at line 221 of file netlink.c.
References CE_GW_A_DST, CE_GW_A_FLAGS, CE_GW_A_MAX, CE_GW_A_SRC, CE_GW_A_TYPE, CE_GW_C_ADD, ce_gw_genl_policy, genl_fam, IFACE_VERSION, nl_sk, NO_FLAG, and USER_HDR_SIZE.
Referenced by main().
 {
     int err = 0;
     struct nl_msg *msg;
     /* create */
     msg = nlmsg_alloc();
     if(msg == NULL) {
         fprintf(stderr,"add: Message allocation failed.\n");
         return -ENOMEM;
     }
     void *user_hdr;
     user_hdr = genlmsg_put(msg, NL_AUTO_PORT, NL_AUTO_SEQ,
                            genl_family_get_id(genl_fam), USER_HDR_SIZE,
                            NO_FLAG, CE_GW_C_ADD, IFACE_VERSION);
     if (user_hdr == NULL)
         fprintf(stderr, "add: Message Haeder creation failed\n");
     if (src_name != NULL) { /* indicates that it is add route command */
         NLA_PUT_STRING(msg, CE_GW_A_SRC, src_name);
         NLA_PUT_STRING(msg, CE_GW_A_DST, dst_name);
     } /* else it is add dev command */
     /* Attributes needed by both, add route and add dev */
     NLA_PUT_U8(msg, CE_GW_A_TYPE, type);
     NLA_PUT_U32(msg, CE_GW_A_FLAGS, flags);
     /* vaildate */
     struct nlmsghdr *msghdr = nlmsg_hdr(msg);
     err = genlmsg_validate(msghdr, USER_HDR_SIZE,
                            CE_GW_A_MAX, ce_gw_genl_policy);
     if (err != 0) {
         fprintf(stderr, "add: Validation of Message Failed: %i\n", err);
         return -1;
     }
     /* send */
     nl_send_auto(nl_sk, msg);
     err = nl_wait_for_ack(nl_sk);
     if (err != 0) {
         fprintf(stderr,
                 "add: ACK is missing or Error returned. "
                 "Operation might fail: %i\n", err);
     }
     nlmsg_free(msg);
     return 0;
 nla_put_failure:
     fprintf(stderr, "Attribute Modification failed: %d\n",-EMSGSIZE);
     nlmsg_free(msg);
     return -EMSGSIZE;
 }
int ce_gw_del (uint32_t id, char * dev_name)
Deletes a device or a route in Kernel Module.
Parameters
id The id of the route you want to delete. param dev_name must be NULL when you want to delete a route.
dev_name The textual name of the virtual device you want to delete. The device must be previously added by ce_gw_add(). param id must be 0 if you want to delete a device.
Precondition
param id must be == 0 OR param dev_name must be == NULL
Return values
0 on success
<0 on failure
See Also
related callbacks: nl_cb_general_errno()
Definition at line 413 of file netlink.c.
References CE_GW_A_DST, CE_GW_A_ID, CE_GW_A_MAX, CE_GW_C_DEL, ce_gw_genl_policy, genl_fam, IFACE_VERSION, nl_sk, NO_FLAG, and USER_HDR_SIZE.
Referenced by main().
 {
     int err;
     struct nl_msg *msg;
     if (id != 0 && dev_name != NULL) {
         err = -EINVAL;
         return err;
     }
     /* create */
     msg = nlmsg_alloc();
     if(msg == NULL) {
         fprintf(stderr,"del: Message allocation failed.\n");
         return -1;
     }
     void *user_hdr;
     user_hdr = genlmsg_put(msg, NL_AUTO_PORT, NL_AUTO_SEQ,
                            genl_family_get_id(genl_fam), USER_HDR_SIZE,
                            NO_FLAG, CE_GW_C_DEL, IFACE_VERSION);
     if (user_hdr == NULL)
         fprintf(stderr, "del: Message Haeder creation failed\n");
     NLA_PUT_U32(msg, CE_GW_A_ID, id);
     if (dev_name != NULL) { /* del dev is called */
         NLA_PUT_STRING(msg, CE_GW_A_DST, dev_name);
     }
     /* vaildate */
     struct nlmsghdr *msghdr = nlmsg_hdr(msg);
     err = genlmsg_validate(msghdr, USER_HDR_SIZE,
                            CE_GW_A_MAX, ce_gw_genl_policy);
     if (err != 0) {
         fprintf(stderr, "del: Validation of Message Failed: %i\n", err);
         return -1;
     }
     /* send */
     nl_send_auto(nl_sk, msg);
     err = nl_wait_for_ack(nl_sk);
     if (err != 0) {
         fprintf(stderr,
                 "add: ACK is missing or Error returned. "
                 "Operation might fail: %i\n", err);
     }
     nlmsg_free(msg);
     return 0;
 nla_put_failure:
     fprintf(stderr, "Attribute Modification failed: %d\n",-EMSGSIZE);
     nlmsg_free(msg);
     return -EMSGSIZE;
 }
int ce_gw_echo (char * message)
send a message and return the received message from Kernel.
Parameters
message A String message you want to send.
Return values
The message you get from the Kernel. NULL on failure.
Definition at line 488 of file netlink.c.
References CE_GW_A_DATA, CE_GW_A_MAX, CE_GW_C_ECHO, ce_gw_echo_answer(), ce_gw_genl_policy, genl_fam, IFACE_VERSION, nl_sk, NO_FLAG, and USER_HDR_SIZE.
Referenced by main().
 {
     int rc; /* return codes */
     struct nl_msg *msg;
     /* create */
     msg = nlmsg_alloc();
     if(msg == NULL) {
         fprintf(stderr,"echo: Message allocation failed.\n");
         return -1;
     }
     void *user_hdr;
     user_hdr = genlmsg_put(msg, NL_AUTO_PORT, NL_AUTO_SEQ,
                            genl_family_get_id(genl_fam), USER_HDR_SIZE,
                            NO_FLAG, CE_GW_C_ECHO, IFACE_VERSION);
     if (user_hdr == NULL)
         fprintf(stderr, "echo: Message Haeder creation failed.\n");
     NLA_PUT_STRING(msg, CE_GW_A_DATA, message);
     /* vaildate */
     struct nlmsghdr *msghdr = nlmsg_hdr(msg);
     if ((rc = genlmsg_validate(msghdr,0,CE_GW_A_MAX, ce_gw_genl_policy)) != 0) {
         fprintf(stderr, "echo: Validation of Message Failed: %i\n", rc);
         return -1;
     }
     /* send */
     nl_socket_disable_auto_ack(nl_sk);
     nl_send_auto(nl_sk, msg);
     // TODO receive
     /* create callback system */
     struct nl_cb *cb = nl_cb_alloc(NL_CB_DEBUG);
     nl_cb_set(cb, NL_CB_MSG_IN, NL_CB_CUSTOM , ce_gw_echo_answer, NULL);
     nl_recvmsgs(nl_sk, cb);
     nl_cb_put(cb);
     nlmsg_free(msg);
     return 0;
 nla_put_failure:
     fprintf(stderr, "Attribute Modification failed: %d\n",-EMSGSIZE);
     nlmsg_free(msg);
     return -1;
 }
int ce_gw_list (uint32_t id)
Print informations of actual active routes to stdout.
Parameters
id set it to 0 if you want to list all routes. Else set it to the id of the route for wich you want the informations printed.
Return values
0 on success
<0 on failure
See Also
related callbacks: nl_cb_list_entry(), nl_cb_list_finish(), nl_cb_general_errno()
Definition at line 345 of file netlink.c.
References CE_GW_A_ID, CE_GW_A_MAX, CE_GW_C_LIST, ce_gw_genl_policy, genl_fam, IFACE_VERSION, nl_cb_general_errno(), nl_cb_list_entry(), nl_cb_list_finish(), nl_sk, NO_FLAG, and USER_HDR_SIZE.
Referenced by main().
 {
     int err;
     struct nl_msg *msg;
     /* create */
     msg = nlmsg_alloc();
     if(msg == NULL) {
         fprintf(stderr,"echo: Message allocation failed.\n");
         return -1;
     }
     void *user_hdr;
     user_hdr = genlmsg_put(msg, NL_AUTO_PORT, NL_AUTO_SEQ,
                            genl_family_get_id(genl_fam), USER_HDR_SIZE,
                            NO_FLAG, CE_GW_C_LIST, IFACE_VERSION);
     if (user_hdr == NULL)
         fprintf(stderr, "echo: Message Haeder creation failed.\n");
     NLA_PUT_U32(msg, CE_GW_A_ID, id);
     /* vaildate */
     struct nlmsghdr *msghdr = nlmsg_hdr(msg);
     err = genlmsg_validate(msghdr, 0, CE_GW_A_MAX, ce_gw_genl_policy);
     if (err != 0) {
         fprintf(stderr, "echo: Validation of Message Failed: %i\n",
                 err);
         return -1;
     }
     /* send */
     nl_socket_disable_auto_ack(nl_sk);
     nl_send_auto(nl_sk, msg);
     /* create callback system */
     struct nl_cb *cb = nl_cb_alloc(NL_CB_DEFAULT);
     nl_cb_set(cb, NL_CB_VALID, NL_CB_CUSTOM, nl_cb_list_entry, NULL);
     nl_cb_set(cb, NL_CB_FINISH, NL_CB_CUSTOM, nl_cb_list_finish, NULL);
     nl_cb_err(cb, NL_CB_CUSTOM, nl_cb_general_errno, NULL);
     printf(" ID       SRC    DST    TYPE   HANDLED  DROPPED  FLAGS\n");
     nl_recvmsgs(nl_sk, cb);
     nl_cb_put(cb);
     nlmsg_free(msg);
     return 0;
 nla_put_failure:
     fprintf(stderr, "Attribute Modification failed: %d\n",-EMSGSIZE);
     nlmsg_free(msg);
     return -1;
 }
void nl_sk_fam_exit (void)
freeing the alloccated memory. The Function free the memory allocated by nl_sk_fam_init().
See Also
nl_sk_fam_init()
Definition at line 601 of file netlink.c.
References genl_fam, and nl_sk.
Referenced by main().
 {
     nl_close(nl_sk);
     genl_family_put(genl_fam);
     nl_socket_free(nl_sk);
 }
int nl_sk_fam_init (void)
creakte socket and family and connect
It creates the netlink socket and connect, as well as the netlink family. This function must called once before any other netlink operation.
See Also
nl_sk_fam_exit()
Return values
0 on success, negative value on failure
Definition at line 547 of file netlink.c.
References CE_GW_A_MAX, GE_FAMILY_NAME, GE_FAMILY_VERSION, genl_fam, nl_cb_general_errno(), nl_sk, and USER_HDR_SIZE.
Referenced by main().
 {
     int err;
     /* create gneric netlink socket */
     nl_sk = nl_socket_alloc();
     if ( nl_sk == NULL ) {
         fprintf (stderr, "Socket allocation failed.\n");
         return -1;
     }
     err = genl_connect(nl_sk);
     if (err != 0) {
         fprintf (stderr, "Connetion to socket failed: %d\n", err);
         return err;
     }
     err = nl_socket_modify_err_cb(nl_sk, NL_CB_CUSTOM,
                                   nl_cb_general_errno, NULL);
     if (err != 0) {
         fprintf (stderr, "Error Callback modification failed: %d\n",
                  err);
     }
     /* create generic netlink family */
     genl_fam = genl_family_alloc();
     if (genl_fam == NULL) {
         fprintf (stderr, "Family allocation failed.\n");
         return -1;
     }
     genl_family_set_name(genl_fam, GE_FAMILY_NAME);
     genl_family_set_version(genl_fam, GE_FAMILY_VERSION);
     genl_family_set_maxattr(genl_fam, CE_GW_A_MAX);
     genl_family_set_hdrsize(genl_fam, USER_HDR_SIZE);
     genl_family_set_id(genl_fam,
                        (err = genl_ctrl_resolve(nl_sk, GE_FAMILY_NAME)));
     if (err < 0) {
         fprintf(stderr,
                 "Could not resolve Netlink Family ID from kernel. "
                 "Is the module loaded?: %d\n", err);
         return err;
     }
     return 0;
 }