can-eth-gw-utils Gateway Utilities: src/cegwsend/cegwsend.c File Reference
cegwsend.c File Reference
#include <linux/version.h>
#include <linux/if_ether.h>
#include <getopt.h>
#include <stdlib.h>
#include <linux/can.h>
#include <string.h>
#include <stdio.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <errno.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <net/ethernet.h>
#include <netpacket/packet.h>
Functions
void convert_to_mac (const char *string1)
static void die (const char *msg)
int main (int argc, char *argv[])
Variables
char * mac
Function Documentation
void convert_to_mac (const char * string1)
convert_to_mac converts a string from the console to a MAC address with the length of 6 bytes
i is used in the for loop
A MAC address has the length of 6 Bytes. We need to allocate enough memory to store it.
Definition at line 23 of file cegwsend.c.
References mac.
Referenced by main().
 {
     int i;
     char* string2;
     mac = (char *) malloc(6);
     mac[0] = strtoul(string1, &string2, 16);
     for(i = 1; i <= 5; i++){
         mac[i] = strtoul(string2 + 1, &string2, 16);
     }
 }
static void die (const char * msg) static
die() is called in case of a failure. It prints the error message and exits the program
Definition at line 44 of file cegwsend.c.
Referenced by main().
 {
     perror(msg);
     exit(EXIT_FAILURE);
 }
int main (int argc, char * argv[])
c is used for calling getopt_long()
src points at the beginning of the memory space in which the MAC address of the message's receiver will be written
dest points at the beginning of the memory space in which the MAC address of the message's sender will be written
type is the identifier of the EtherType
raw_index points at the beginning of the raw data in argv[]. If raw_index == -1, then no data exists
name_index is the index of argv in which the name of the ethernet device begins. If name_index == -1, then there is no name
getopt_long is used here for reading the arguments from the command line
source MAC address
destination MAC address
packet type ID field
raw data
name of the network interface
Detect the end of the options.
If this option set a flag, do nothing else now.
convert the argument to a valid MAC address
convert_to_mac writes the address down in mac. It must be stored in src now.
convert the argument to al valid MAC address
convert_to_mac writes the address down in mac. It must be stored in dest now.
The EtherType is defined by a number with the length of 2 Bytes (e. g. 0x8000 for the Internet Protocol). The argument from the console must be converted to a number. This happens here.
The EtherType of Internet Protocol, Version 4 is 0x0800
The EtherType of Internet Protocol, Version 6 is 0x86DD
The EtherType of Controller Area Network is 0x000C
The EtherType of CAN flexible data rate is 0x000D
If the identifier was typed in like "0x1234" we cut off the 0x and convert the number. If instead it was written down like "1234" we simply convert the argument from the console to a number.
getopt_long already printed error message-
mac is not needed anymore
Create the AF_PACKET socket
In case of a failure the allocated memory must be freed and die is called
Name/index number of the interface If there is no name, we have a problem and the program must end
Construct the destination address
dest is not needed anymore
Now, finally, let's send the data, if it exists, of course
Nerver forget to free the allocated memory
Definition at line 50 of file cegwsend.c.
References convert_to_mac(), die(), and mac.
 {
     int c;
     char *src;
     src = (char *) malloc(6);
     char *dest;
     dest = (char *) malloc(6);
     ushort type;
     int raw_index = -1;
     int name_index = -1;
     while (1){
         static struct option long_options[] = {
             {"src", required_argument, 0, 's'},
             {"dst", required_argument, 0, 'd'},
             {"type", required_argument, 0, 't'},
             {"raw", required_argument, 0, 'r'},
             {"name", required_argument, 0, 'n'},
             {0, 0, 0, 0}
         };
         /* getopt_long stores the option index here. */
         int option_index = 0;
         c = getopt_long(argc, argv, "s:d:t:r:n:", long_options, &option_index);
         if(c == -1)
             break;
         switch (c){
             case 0:
                 if(long_options[option_index].flag != 0)
                     break;
                 printf("option %s", long_options[option_index].name);
                 if(optarg)
                     printf(" with arg %s", optarg);
                 printf("\n");
                 break;
             case 's':
                 printf("option -s with value `%s'\n", optarg);
                 convert_to_mac(optarg);
                 memcpy(src, mac, 6);
                 break;
             case 'd':
                 printf("option -d with value `%s'\n", optarg);
                 convert_to_mac(optarg);
                 memcpy(dest, mac, 6);
                 break;
             case 't':
                 printf("option -t with value `%s'\n", optarg);
                 if(strcmp(optarg, "ipv4") == 0){
                     type = 0x0800;
                 } else if(strcmp(optarg, "ipv6") == 0){
                     type = 0x86DD;
                 } else if(strcmp(optarg, "can") == 0){
                     type = 0x000C;
                 } else if(strcmp(optarg, "canfd") == 0){
                     type = 0x000D;
                 } else if(strncmp(optarg, "0x", 2) == 0){
                     type = strtoul(optarg + 2, &optarg, 16);
                 } else {
                     type = strtoul(optarg, &optarg, 16);
                 }
                 break;
             case 'r':
                 printf("option -r with value `%s'\n", optarg);
                 raw_index = optind - 1;
                 break;
             case 'n':
                 printf("option -n with value `%s'\n", optarg);
                 name_index = optind - 1;
                 break;
             case '?':
                 break;
             default:
                 abort();
         }
     }
     free(mac);
     printf("source: %hhX", *src);
     printf(":%hhX", *(src + 1));
     printf(":%hhX", *(src + 2));
     printf(":%hhX", *(src + 3));
     printf(":%hhX", *(src + 4));
     printf(":%hhX\n", *(src + 5));
     printf("destination: %hhX", *dest);
     printf(":%hhX", *(dest + 1));
     printf(":%hhX", *(dest + 2));
     printf(":%hhX", *(dest + 3));
     printf(":%hhX", *(dest + 4));
     printf(":%hhX\n", *(dest + 5));
     printf("type: %hX \n", type);
     int fd = socket(AF_PACKET, SOCK_DGRAM, htons(type));
     if (fd == -1){
         free(dest);
         free(src);
         die(strerror(errno));
     }
     if(name_index == -1){
         free(dest);
         free(src);
         die("name/index number of the network interface required");
     }
     struct ifreq ifr;
     size_t if_name_len = strlen(argv[name_index]);
     if(if_name_len < sizeof(ifr.ifr_name)){
         memcpy(ifr.ifr_name, argv[name_index], if_name_len);
         ifr.ifr_name[if_name_len] = 0;
     } else {
         printf("sizeof(ifr.ifr_name): %d", sizeof(ifr.ifr_name));
         printf(" sollte groesser sein als if_name_len: %d", if_name_len);
         free(src);
         free(dest);
         die("interface name is too long");
     }
     if(ioctl(fd, SIOCGIFINDEX, &ifr) == -1){
         free(src);
         free(dest);
         die(strerror(errno));
     }
     int ifindex = ifr.ifr_ifindex;
     struct sockaddr_ll addr = {0};
     addr.sll_family = AF_PACKET;
     addr.sll_ifindex = ifindex;
     addr.sll_halen = ETHER_ADDR_LEN;
     addr.sll_protocol = htons(type);
     memcpy(addr.sll_addr, dest, ETHER_ADDR_LEN);
     free(dest);
     if(raw_index == -1){
         free(src);
         die("No data to be sent");
     }
     if(sendto(fd, argv[raw_index], strlen(argv[raw_index]), 0, (struct sockaddr*)&addr, sizeof(addr)) == -1){
         free(src);
         die(strerror(errno));
     }
     free(src);
     return 0;
 }
Variable Documentation
char* mac
Definition at line 17 of file cegwsend.c.
Referenced by convert_to_mac(), and main().