can-eth-gw-utils Utilities: Callbacks
Callbacks
Core
Control Area Network - Ethernet - Gateway - Control (Utility)
Functions
int main (int argc, char *argv[])
creates an Ethernet package and sends it to a device.
int nl_cb_general_errno (struct sockaddr_nl *nla, struct nlmsgerr *nlerr, void *arg)
A callback wich prints the errno to stderr.
int nl_cb_list_entry (struct nl_msg *msg, void *arg)
will be called for every multipart message and prints informations to stdout.
int nl_cb_list_finish (struct nl_msg *msg, void *arg)
will be called at the end of a multipart message.
int nl_cb_echo_answer (struct nl_msg *msg, void *arg)
Callback witch receive the message sen bach by kernel.
Variables
int verbose_flag
int bidirectional_flag = 0
uint32_t flags = 0
uint8_t gw_type = TYPE_NET
Detailed Description
Control Area Network - Ethernet - Gateway - Control (Utility)
The gateway is configured here.
Function Documentation
int main (int argc, char * argv[])
creates an Ethernet package and sends it to a device.
Parameters
argc counts the arguments from the console param argv each word from the console is written down in this array
Returns
EXIT_SUCCESS if the program was succesful, EXIT_FAILURE if an error occured
Definition at line 48 of file main.c.
References bidirectional_flag, ce_gw_add(), ce_gw_del(), ce_gw_echo(), ce_gw_list(), F_CAN_FD, nl_sk_fam_exit(), nl_sk_fam_init(), TYPE_ETH, TYPE_NET, TYPE_NONE, TYPE_TCP, TYPE_UDP, and verbose_flag.
 {
     int err = 0;
     err = nl_sk_fam_init();
     if (err != 0) {
         fprintf(stderr,
                 "Error during initialisation of Socket or Netlink "
                 "Family: %d\n", err);
         return EXIT_FAILURE;
     }
     int c;
     while (1) {
         static struct option long_options[] = {
             /* These options set a flag. */
             /* These options don't set a flag.
                We distinguish them by their indices. */
             {"bidirectional", no_argument, 0, 'b'},
             {"can-fd",        no_argument, 0, 'f'},
             {"type",    required_argument, 0, 't'},
             {0, 0, 0, 0},
         };
         /* getopt_long stores the option index here. */
         int option_index = 0;
         c = getopt_long (argc, argv, "bft:",
                          long_options, &option_index);
         /* Detect the end of the options. */
         if (c == -1)
             break;
         switch (c) {
         case 0:
             /* If this option set a flag, do nothing else now. */
             if (long_options[option_index].flag != 0)
                 break;
             printf ("option %s", long_options[option_index].name);
             if (optarg)
                 printf (" with arg %s", optarg);
             printf ("\n");
             break;
         case 'b':
             bidirectional_flag = 1;
             break;
         case 'f':
             flags = flags | F_CAN_FD;
             break;
         case 't':
             if(!strcmp(optarg, "none")) {
                 gw_type = TYPE_NONE;
             } else if(!strcmp(optarg, "eth")) {
                 gw_type = TYPE_ETH;
             } else if (!strcmp(optarg, "net")) {
                 gw_type = TYPE_NET;
             } else if (!strcmp(optarg, "tcp")) {
                 gw_type = TYPE_TCP;
             } else if (!strcmp(optarg, "udp")) {
                 gw_type = TYPE_UDP;
             } else {
                 fprintf(stderr, "%s: Supported Types: "
                         "none, eth, net, tcp, udp\n", argv[0]);
                 return EXIT_FAILURE;
             }
             break;
         case '?':
             /* getopt_long already printed an error message. */
             break;
         default:
             abort();
         }
     }
     /* Instead of reporting ‘--verbose’
        and ‘--brief’ as they are encountered,
        we report the final status resulting from them. */
     if (verbose_flag)
         puts ("verbose flag is set\n");
     /***************************************************/
     /* Remaining command line arguments (not options). */
     /***************************************************/
     while (optind < argc) {
         /* add route SRC DST */
         if(!strcmp(argv[optind], "add") &&
             !strcmp(argv[optind+1], "route") && optind+4 <= argc) {
             err = ce_gw_add(argv[optind+3], argv[optind+2],
                             gw_type, flags);
             if (err != 0) {
                 fprintf(stderr, "%s: Error during add: %d",
                         argv[0], err);
                 return EXIT_FAILURE;
             }
             if (bidirectional_flag == 1) {
                 err = ce_gw_add(argv[optind+2], argv[optind+3],
                                 gw_type, flags);
                 if (err != 0) {
                     fprintf(stderr, "%s: Error during "
                             "add: %d", argv[0], err);
                     return EXIT_FAILURE;
                 }
             }
             optind += 4;
             /* add dev [NAME] */
         } else if (!strcmp(argv[optind], "add") &&
                    !strcmp(argv[optind+1], "dev") && optind+2 <= argc) {
             if (optind+3 <= argc) {
                 err = ce_gw_add(argv[optind+2], NULL, gw_type,
                                 flags);
                 if (err != 0) {
                     fprintf(stderr, "%s: Error during "
                             "add: %d", argv[0], err);
                     return EXIT_FAILURE;
                 }
                 optind += 3;
             } else {
                 err = ce_gw_add("cegw%d", NULL, gw_type, flags);
                 if (err != 0) {
                     fprintf(stderr, "%s: Error during "
                             "add: %d", argv[0], err);
                     return EXIT_FAILURE;
                 }
                 optind += 2;
             }
             /* del route ID */
         } else if(!strcmp(argv[optind], "del") &&
                   !strcmp(argv[optind+1], "route") && optind+3 <= argc ) {
             uintmax_t num = strtoumax(argv[optind+2], NULL, 0);
             if (num == UINTMAX_MAX && errno == ERANGE) {
                 fprintf(stderr, "%s: Error: Parameter "
                         "ID is not a number %d\n",
                         argv[0], errno);
             }
             err = ce_gw_del((uint32_t) num, NULL);
             if (err != 0) {
                 fprintf(stderr, "%s: Error during del: %d\n",
                         argv[0], err);
                 return EXIT_FAILURE;
             }
             optind += 3;
             /* del dev DEV_NAME */
         } else if(!strcmp(argv[optind], "del") &&
                   !strcmp(argv[optind+1], "dev") && optind+3 <= argc ) {
             err = ce_gw_del(0, argv[optind+2]);
             if (err != 0) {
                 fprintf(stderr, "%s: Error during del: %d\n",
                         argv[0], err);
                 return EXIT_FAILURE;
             }
             optind += 3;
             /* echo MSG */
         } else if(!strcmp(argv[optind], "echo") && optind+2 <= argc) {
             err = ce_gw_echo(argv[optind+1]);
             if (err != 0) {
                 fprintf(stderr, "%s: Error during echo: %d",
                         argv[0], err);
                 return EXIT_FAILURE;
             }
             optind += 2;
             /* route */
         } else if(!strcmp(argv[optind], "route") && optind+1 <= argc) {
             if (optind+2 <= argc) {
                 uintmax_t num = strtoumax(argv[optind+1],
                                           NULL, 0);
                 if (num == UINTMAX_MAX && errno == ERANGE) {
                     fprintf(stderr, "%s: Error: Parameter "
                             "ID is not a number %d\n",
                             argv[0], errno);
                 }
                 err = ce_gw_list(num);
                 optind += 2;
             } else {
                 err = ce_gw_list(0);
                 optind += 1;
             }
             if (err != 0) {
                 fprintf(stderr, "%s: Error during list: %d",
                         argv[0], err);
                 return EXIT_FAILURE;
             }
             /* unrecognized command */
         } else {
             optind += 1;
             while(optind < argc) {
                 printf(" %s", argv[optind]);
                 optind += 1;
             }
             printf("'\n");
             return EXIT_FAILURE;
         }
     }
     nl_sk_fam_exit();
     return EXIT_SUCCESS;
 }
int nl_cb_echo_answer (struct nl_msg * msg, void * arg)
Callback witch receive the message sen bach by kernel.
Parameters
msg Netlink Message arg a file
Return values
NL_OK
See Also
defined as callback in ce_gw_echo()
Definition at line 448 of file netlink.c.
Referenced by ce_gw_echo().
 {
     struct nlmsghdr *msghdr = nlmsg_hdr(msg);
     struct genlmsghdr *gemsghdr =  nlmsg_data(msghdr);
     struct nlattr *a_msg = genlmsg_attrdata(gemsghdr, 0);
     char * a_msg_data = (char *) nla_data(a_msg);
     printf("kernel says: %s\n", a_msg_data);
     return NL_OK;
 }
int nl_cb_general_errno (struct sockaddr_nl * nla, struct nlmsgerr * nlerr, void * arg)
A callback wich prints the errno to stderr.
Parameters
nla Socket address informations
nlerr error Message arg a file
A callback wich prints the errno to stderr. In nl_sk_fam_init() it is delcared as standart error callback.
Return values
NL_STOP
Definition at line 203 of file netlink.c.
Referenced by ce_gw_list(), and nl_sk_fam_init().
 {
     int err = nlerr->error;
     fprintf(stderr, "NETLINK returned Error: %s\n", strerror(err));
     return NL_STOP;
 }
int nl_cb_list_entry (struct nl_msg * msg, void * arg)
will be called for every multipart message and prints informations to stdout.
Parameters
msg Netlink Message arg a file
Return values
NL_OK
See Also
defined as callback in ce_gw_list()
Definition at line 335 of file netlink.c.
References CE_GW_A_DROP, CE_GW_A_DST, CE_GW_A_FLAGS, CE_GW_A_HNDL, CE_GW_A_ID, CE_GW_A_MAX, CE_GW_A_SRC, CE_GW_A_TYPE, ce_gw_genl_policy, enum2str(), flags2str(), flags_array, type_array, TYPE_MAX, and USER_HDR_SIZE.
Referenced by ce_gw_list().
 {
     int err;
     struct nlmsghdr *msghdr = nlmsg_hdr(msg);
     struct nlattr *attrs[CE_GW_A_MAX+1];
     err = genlmsg_parse(msghdr, USER_HDR_SIZE, attrs,
                         CE_GW_A_MAX, ce_gw_genl_policy);
     if (err < 0)
         fprintf(stderr, "ERROR Kernel Message Parsing Failed\n");
     char *a_msg_src_data = (char *)nla_data(attrs[CE_GW_A_SRC]);
     char *a_msg_dst_data = (char *)nla_data(attrs[CE_GW_A_DST]);
     uint32_t *a_msg_id_data = (uint32_t *)nla_data(attrs[CE_GW_A_ID]);
     uint32_t *a_msg_flags_data = (uint32_t *)nla_data(attrs[CE_GW_A_FLAGS]);
     uint8_t *a_msg_type_data = (uint8_t *)nla_data(attrs[CE_GW_A_TYPE]);
     uint32_t *a_msg_hndl_data = (uint32_t *)nla_data(attrs[CE_GW_A_HNDL]);
     uint32_t *a_msg_drop_data = (uint32_t *)nla_data(attrs[CE_GW_A_DROP]);
     char *type_str;
     type_str = enum2str(*a_msg_type_data, type_array, 6, TYPE_MAX);
     char *flags_str;
     /* 256 should be big enough */
     flags_str = flags2str(*a_msg_flags_data, flags_array, 256);
     printf(" %-8d %-6s %-6s %-6s %-8d %-8d %s\n", *a_msg_id_data,
            a_msg_src_data, a_msg_dst_data, type_str, *a_msg_hndl_data,
            *a_msg_drop_data, flags_str);
     free(type_str);
     free(flags_str);
     return NL_OK;
 }
int nl_cb_list_finish (struct nl_msg * msg, void * arg)
will be called at the end of a multipart message.
Parameters
msg Netlink Message arg a file
Return values
NL_STOP
See Also
defined as callback in ce_gw_list()
Definition at line 379 of file netlink.c.
Referenced by ce_gw_list().
 {
     return NL_STOP;
 }
Variable Documentation
int bidirectional_flag = 0
Definition at line 44 of file main.c.
Referenced by main().
uint32_t flags = 0
Definition at line 45 of file main.c.
uint8_t gw_type = TYPE_NET
Definition at line 46 of file main.c.
int verbose_flag
Definition at line 43 of file main.c.
Referenced by main().